# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import video_pb2 as proto_dot_video__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/video_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VideoProcessorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessFrame = channel.stream_stream(
                '/VideoProcessor/ProcessFrame',
                request_serializer=proto_dot_video__pb2.VideoFrame.SerializeToString,
                response_deserializer=proto_dot_video__pb2.AnalysisResult.FromString,
                _registered_method=True)


class VideoProcessorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessFrame(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessFrame': grpc.stream_stream_rpc_method_handler(
                    servicer.ProcessFrame,
                    request_deserializer=proto_dot_video__pb2.VideoFrame.FromString,
                    response_serializer=proto_dot_video__pb2.AnalysisResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'VideoProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('VideoProcessor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VideoProcessor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessFrame(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/VideoProcessor/ProcessFrame',
            proto_dot_video__pb2.VideoFrame.SerializeToString,
            proto_dot_video__pb2.AnalysisResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
