# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/video.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/video.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/video.proto\"r\n\nVideoFrame\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x1e\n\nalgorithms\x18\x03 \x03(\x0b\x32\n.Algorithm\x12\x0e\n\x06height\x18\x04 \x01(\x03\x12\r\n\x05width\x18\x05 \x01(\x03\"\x85\x01\n\x0e\x41nalysisResult\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x1c\n\nface_boxes\x18\x02 \x03(\x0b\x32\x08.FaceBox\x12 \n\x0cperson_boxes\x18\x03 \x03(\x0b\x32\n.PersonBox\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\t\x12\x12\n\nimage_data\x18\x05 \x01(\x0c\"\xbf\x01\n\x07\x46\x61\x63\x65\x42ox\x12\r\n\x05label\x18\x01 \x01(\t\x12\x18\n\x08minPoint\x18\x02 \x01(\x0b\x32\x06.Point\x12\x18\n\x08maxPoint\x18\x03 \x01(\x0b\x32\x06.Point\x12\r\n\x05score\x18\x04 \x01(\x02\x12\x10\n\x08track_id\x18\x05 \x01(\x03\x12\x0f\n\x07\x66\x61\x63\x65_id\x18\x06 \x01(\x03\x12\x15\n\rexpression_id\x18\x07 \x01(\x03\x12\x1a\n\x12\x65xpression_feature\x18\x08 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\t \x01(\t\"\xc4\x01\n\tPersonBox\x12\r\n\x05label\x18\x01 \x01(\t\x12\x18\n\x08minPoint\x18\x02 \x01(\x0b\x32\x06.Point\x12\x18\n\x08maxPoint\x18\x03 \x01(\x0b\x32\x06.Point\x12\x16\n\x06points\x18\x04 \x03(\x0b\x32\x06.Point\x12\r\n\x05score\x18\x05 \x01(\x02\x12\x10\n\x08track_id\x18\x06 \x01(\x03\x12\x13\n\x0b\x61ttitude_id\x18\x07 \x01(\x03\x12\x18\n\x10\x61ttitude_feature\x18\x08 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\t \x01(\t\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"5\n\tAlgorithm\x12\x0c\n\x04type\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t2B\n\x0eVideoProcessor\x12\x30\n\x0cProcessFrame\x12\x0b.VideoFrame\x1a\x0f.AnalysisResult(\x01\x30\x01\x42\x1f\n\x0f\x63om.saigou.grpcB\nVideoProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.video_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017com.saigou.grpcB\nVideoProtoP\001'
  _globals['_VIDEOFRAME']._serialized_start=21
  _globals['_VIDEOFRAME']._serialized_end=135
  _globals['_ANALYSISRESULT']._serialized_start=138
  _globals['_ANALYSISRESULT']._serialized_end=271
  _globals['_FACEBOX']._serialized_start=274
  _globals['_FACEBOX']._serialized_end=465
  _globals['_PERSONBOX']._serialized_start=468
  _globals['_PERSONBOX']._serialized_end=664
  _globals['_POINT']._serialized_start=666
  _globals['_POINT']._serialized_end=695
  _globals['_ALGORITHM']._serialized_start=697
  _globals['_ALGORITHM']._serialized_end=750
  _globals['_VIDEOPROCESSOR']._serialized_start=752
  _globals['_VIDEOPROCESSOR']._serialized_end=818
# @@protoc_insertion_point(module_scope)
