// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: video.proto
// Protobuf Java Version: 4.28.0

package com.saigou.grpc;

public interface AlgorithmOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Algorithm)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 算法类型
   * </pre>
   *
   * <code>int64 type = 1;</code>
   * @return The type.
   */
  long getType();

  /**
   * <pre>
   * 算法名称
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  String getName();
  /**
   * <pre>
   * 算法名称
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * 算法参数
   * </pre>
   *
   * <code>string data = 3;</code>
   * @return The data.
   */
  String getData();
  /**
   * <pre>
   * 算法参数
   * </pre>
   *
   * <code>string data = 3;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
