// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: video.proto
// Protobuf Java Version: 4.28.0

package com.saigou.grpc;

/**
 * Protobuf type {@code AnalysisResult}
 */
public final class AnalysisResult extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:AnalysisResult)
        AnalysisResultOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 0,
      /* suffix= */ "",
      AnalysisResult.class.getName());
  }
  // Use AnalysisResult.newBuilder() to construct.
  private AnalysisResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AnalysisResult() {
    boxes_ = java.util.Collections.emptyList();
    data_ = "";
    imageData_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return VideoProto.internal_static_AnalysisResult_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return VideoProto.internal_static_AnalysisResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            AnalysisResult.class, AnalysisResult.Builder.class);
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 1;
  private long timestamp_ = 0L;
  /**
   * <pre>
   * 时间戳（毫秒）
   * </pre>
   *
   * <code>int64 timestamp = 1;</code>
   * @return The timestamp.
   */
  @Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int BOXES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<BoundingBox> boxes_;
  /**
   * <pre>
   * 检测框
   * </pre>
   *
   * <code>repeated .BoundingBox boxes = 2;</code>
   */
  @Override
  public java.util.List<BoundingBox> getBoxesList() {
    return boxes_;
  }
  /**
   * <pre>
   * 检测框
   * </pre>
   *
   * <code>repeated .BoundingBox boxes = 2;</code>
   */
  @Override
  public java.util.List<? extends BoundingBoxOrBuilder>
      getBoxesOrBuilderList() {
    return boxes_;
  }
  /**
   * <pre>
   * 检测框
   * </pre>
   *
   * <code>repeated .BoundingBox boxes = 2;</code>
   */
  @Override
  public int getBoxesCount() {
    return boxes_.size();
  }
  /**
   * <pre>
   * 检测框
   * </pre>
   *
   * <code>repeated .BoundingBox boxes = 2;</code>
   */
  @Override
  public BoundingBox getBoxes(int index) {
    return boxes_.get(index);
  }
  /**
   * <pre>
   * 检测框
   * </pre>
   *
   * <code>repeated .BoundingBox boxes = 2;</code>
   */
  @Override
  public BoundingBoxOrBuilder getBoxesOrBuilder(
      int index) {
    return boxes_.get(index);
  }

  public static final int DATA_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile Object data_ = "";
  /**
   * <pre>
   * 算法返回数据
   * </pre>
   *
   * <code>string data = 3;</code>
   * @return The data.
   */
  @Override
  public String getData() {
    Object ref = data_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      data_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 算法返回数据
   * </pre>
   *
   * <code>string data = 3;</code>
   * @return The bytes for data.
   */
  @Override
  public com.google.protobuf.ByteString
      getDataBytes() {
    Object ref = data_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      data_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMAGE_DATA_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString imageData_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes image_data = 4;</code>
   * @return The imageData.
   */
  @Override
  public com.google.protobuf.ByteString getImageData() {
    return imageData_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (timestamp_ != 0L) {
      output.writeInt64(1, timestamp_);
    }
    for (int i = 0; i < boxes_.size(); i++) {
      output.writeMessage(2, boxes_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(data_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, data_);
    }
    if (!imageData_.isEmpty()) {
      output.writeBytes(4, imageData_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, timestamp_);
    }
    for (int i = 0; i < boxes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, boxes_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(data_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, data_);
    }
    if (!imageData_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, imageData_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof AnalysisResult)) {
      return super.equals(obj);
    }
    AnalysisResult other = (AnalysisResult) obj;

    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getBoxesList()
        .equals(other.getBoxesList())) return false;
    if (!getData()
        .equals(other.getData())) return false;
    if (!getImageData()
        .equals(other.getImageData())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    if (getBoxesCount() > 0) {
      hash = (37 * hash) + BOXES_FIELD_NUMBER;
      hash = (53 * hash) + getBoxesList().hashCode();
    }
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (37 * hash) + IMAGE_DATA_FIELD_NUMBER;
    hash = (53 * hash) + getImageData().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static AnalysisResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AnalysisResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AnalysisResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AnalysisResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AnalysisResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AnalysisResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AnalysisResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static AnalysisResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static AnalysisResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static AnalysisResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static AnalysisResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static AnalysisResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(AnalysisResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AnalysisResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AnalysisResult)
          AnalysisResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return VideoProto.internal_static_AnalysisResult_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return VideoProto.internal_static_AnalysisResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AnalysisResult.class, AnalysisResult.Builder.class);
    }

    // Construct using com.saigou.grpc.AnalysisResult.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      timestamp_ = 0L;
      if (boxesBuilder_ == null) {
        boxes_ = java.util.Collections.emptyList();
      } else {
        boxes_ = null;
        boxesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      data_ = "";
      imageData_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return VideoProto.internal_static_AnalysisResult_descriptor;
    }

    @Override
    public AnalysisResult getDefaultInstanceForType() {
      return AnalysisResult.getDefaultInstance();
    }

    @Override
    public AnalysisResult build() {
      AnalysisResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public AnalysisResult buildPartial() {
      AnalysisResult result = new AnalysisResult(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(AnalysisResult result) {
      if (boxesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          boxes_ = java.util.Collections.unmodifiableList(boxes_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.boxes_ = boxes_;
      } else {
        result.boxes_ = boxesBuilder_.build();
      }
    }

    private void buildPartial0(AnalysisResult result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.timestamp_ = timestamp_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.data_ = data_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.imageData_ = imageData_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof AnalysisResult) {
        return mergeFrom((AnalysisResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(AnalysisResult other) {
      if (other == AnalysisResult.getDefaultInstance()) return this;
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (boxesBuilder_ == null) {
        if (!other.boxes_.isEmpty()) {
          if (boxes_.isEmpty()) {
            boxes_ = other.boxes_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureBoxesIsMutable();
            boxes_.addAll(other.boxes_);
          }
          onChanged();
        }
      } else {
        if (!other.boxes_.isEmpty()) {
          if (boxesBuilder_.isEmpty()) {
            boxesBuilder_.dispose();
            boxesBuilder_ = null;
            boxes_ = other.boxes_;
            bitField0_ = (bitField0_ & ~0x00000002);
            boxesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getBoxesFieldBuilder() : null;
          } else {
            boxesBuilder_.addAllMessages(other.boxes_);
          }
        }
      }
      if (!other.getData().isEmpty()) {
        data_ = other.data_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getImageData() != com.google.protobuf.ByteString.EMPTY) {
        setImageData(other.getImageData());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              BoundingBox m =
                  input.readMessage(
                      BoundingBox.parser(),
                      extensionRegistry);
              if (boxesBuilder_ == null) {
                ensureBoxesIsMutable();
                boxes_.add(m);
              } else {
                boxesBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              data_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              imageData_ = input.readBytes();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long timestamp_ ;
    /**
     * <pre>
     * 时间戳（毫秒）
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    @Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * 时间戳（毫秒）
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 时间戳（毫秒）
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000001);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<BoundingBox> boxes_ =
      java.util.Collections.emptyList();
    private void ensureBoxesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        boxes_ = new java.util.ArrayList<BoundingBox>(boxes_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
            BoundingBox, BoundingBox.Builder, BoundingBoxOrBuilder> boxesBuilder_;

    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .BoundingBox boxes = 2;</code>
     */
    public java.util.List<BoundingBox> getBoxesList() {
      if (boxesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(boxes_);
      } else {
        return boxesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .BoundingBox boxes = 2;</code>
     */
    public int getBoxesCount() {
      if (boxesBuilder_ == null) {
        return boxes_.size();
      } else {
        return boxesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .BoundingBox boxes = 2;</code>
     */
    public BoundingBox getBoxes(int index) {
      if (boxesBuilder_ == null) {
        return boxes_.get(index);
      } else {
        return boxesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .BoundingBox boxes = 2;</code>
     */
    public Builder setBoxes(
        int index, BoundingBox value) {
      if (boxesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBoxesIsMutable();
        boxes_.set(index, value);
        onChanged();
      } else {
        boxesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .BoundingBox boxes = 2;</code>
     */
    public Builder setBoxes(
        int index, BoundingBox.Builder builderForValue) {
      if (boxesBuilder_ == null) {
        ensureBoxesIsMutable();
        boxes_.set(index, builderForValue.build());
        onChanged();
      } else {
        boxesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .BoundingBox boxes = 2;</code>
     */
    public Builder addBoxes(BoundingBox value) {
      if (boxesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBoxesIsMutable();
        boxes_.add(value);
        onChanged();
      } else {
        boxesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .BoundingBox boxes = 2;</code>
     */
    public Builder addBoxes(
        int index, BoundingBox value) {
      if (boxesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBoxesIsMutable();
        boxes_.add(index, value);
        onChanged();
      } else {
        boxesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .BoundingBox boxes = 2;</code>
     */
    public Builder addBoxes(
        BoundingBox.Builder builderForValue) {
      if (boxesBuilder_ == null) {
        ensureBoxesIsMutable();
        boxes_.add(builderForValue.build());
        onChanged();
      } else {
        boxesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .BoundingBox boxes = 2;</code>
     */
    public Builder addBoxes(
        int index, BoundingBox.Builder builderForValue) {
      if (boxesBuilder_ == null) {
        ensureBoxesIsMutable();
        boxes_.add(index, builderForValue.build());
        onChanged();
      } else {
        boxesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .BoundingBox boxes = 2;</code>
     */
    public Builder addAllBoxes(
        Iterable<? extends BoundingBox> values) {
      if (boxesBuilder_ == null) {
        ensureBoxesIsMutable();
        addAll(
            values, boxes_);
        onChanged();
      } else {
        boxesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .BoundingBox boxes = 2;</code>
     */
    public Builder clearBoxes() {
      if (boxesBuilder_ == null) {
        boxes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        boxesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .BoundingBox boxes = 2;</code>
     */
    public Builder removeBoxes(int index) {
      if (boxesBuilder_ == null) {
        ensureBoxesIsMutable();
        boxes_.remove(index);
        onChanged();
      } else {
        boxesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .BoundingBox boxes = 2;</code>
     */
    public BoundingBox.Builder getBoxesBuilder(
        int index) {
      return getBoxesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .BoundingBox boxes = 2;</code>
     */
    public BoundingBoxOrBuilder getBoxesOrBuilder(
        int index) {
      if (boxesBuilder_ == null) {
        return boxes_.get(index);  } else {
        return boxesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .BoundingBox boxes = 2;</code>
     */
    public java.util.List<? extends BoundingBoxOrBuilder>
         getBoxesOrBuilderList() {
      if (boxesBuilder_ != null) {
        return boxesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(boxes_);
      }
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .BoundingBox boxes = 2;</code>
     */
    public BoundingBox.Builder addBoxesBuilder() {
      return getBoxesFieldBuilder().addBuilder(
          BoundingBox.getDefaultInstance());
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .BoundingBox boxes = 2;</code>
     */
    public BoundingBox.Builder addBoxesBuilder(
        int index) {
      return getBoxesFieldBuilder().addBuilder(
          index, BoundingBox.getDefaultInstance());
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .BoundingBox boxes = 2;</code>
     */
    public java.util.List<BoundingBox.Builder>
         getBoxesBuilderList() {
      return getBoxesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
            BoundingBox, BoundingBox.Builder, BoundingBoxOrBuilder>
        getBoxesFieldBuilder() {
      if (boxesBuilder_ == null) {
        boxesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                BoundingBox, BoundingBox.Builder, BoundingBoxOrBuilder>(
                boxes_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        boxes_ = null;
      }
      return boxesBuilder_;
    }

    private Object data_ = "";
    /**
     * <pre>
     * 算法返回数据
     * </pre>
     *
     * <code>string data = 3;</code>
     * @return The data.
     */
    public String getData() {
      Object ref = data_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        data_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 算法返回数据
     * </pre>
     *
     * <code>string data = 3;</code>
     * @return The bytes for data.
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 算法返回数据
     * </pre>
     *
     * <code>string data = 3;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      data_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 算法返回数据
     * </pre>
     *
     * <code>string data = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      data_ = getDefaultInstance().getData();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 算法返回数据
     * </pre>
     *
     * <code>string data = 3;</code>
     * @param value The bytes for data to set.
     * @return This builder for chaining.
     */
    public Builder setDataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      data_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString imageData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes image_data = 4;</code>
     * @return The imageData.
     */
    @Override
    public com.google.protobuf.ByteString getImageData() {
      return imageData_;
    }
    /**
     * <code>bytes image_data = 4;</code>
     * @param value The imageData to set.
     * @return This builder for chaining.
     */
    public Builder setImageData(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      imageData_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bytes image_data = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearImageData() {
      bitField0_ = (bitField0_ & ~0x00000008);
      imageData_ = getDefaultInstance().getImageData();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:AnalysisResult)
  }

  // @@protoc_insertion_point(class_scope:AnalysisResult)
  private static final AnalysisResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new AnalysisResult();
  }

  public static AnalysisResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AnalysisResult>
      PARSER = new com.google.protobuf.AbstractParser<AnalysisResult>() {
    @Override
    public AnalysisResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AnalysisResult> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<AnalysisResult> getParserForType() {
    return PARSER;
  }

  @Override
  public AnalysisResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

