// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: video.proto
// Protobuf Java Version: 4.28.0

package com.saigou.grpc;

/**
 * Protobuf type {@code AnalysisResult}
 */
public final class AnalysisResult extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:AnalysisResult)
    AnalysisResultOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 0,
      /* suffix= */ "",
      AnalysisResult.class.getName());
  }
  // Use AnalysisResult.newBuilder() to construct.
  private AnalysisResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AnalysisResult() {
    faceBoxes_ = java.util.Collections.emptyList();
    personBoxes_ = java.util.Collections.emptyList();
    data_ = "";
    imageData_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return VideoProto.internal_static_AnalysisResult_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return VideoProto.internal_static_AnalysisResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            AnalysisResult.class, Builder.class);
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 1;
  private long timestamp_ = 0L;
  /**
   * <pre>
   * 时间戳（毫秒）
   * </pre>
   *
   * <code>int64 timestamp = 1;</code>
   * @return The timestamp.
   */
  @Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int FACE_BOXES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<FaceBox> faceBoxes_;
  /**
   * <pre>
   * 检测框
   * </pre>
   *
   * <code>repeated .FaceBox face_boxes = 2;</code>
   */
  @Override
  public java.util.List<FaceBox> getFaceBoxesList() {
    return faceBoxes_;
  }
  /**
   * <pre>
   * 检测框
   * </pre>
   *
   * <code>repeated .FaceBox face_boxes = 2;</code>
   */
  @Override
  public java.util.List<? extends FaceBoxOrBuilder>
      getFaceBoxesOrBuilderList() {
    return faceBoxes_;
  }
  /**
   * <pre>
   * 检测框
   * </pre>
   *
   * <code>repeated .FaceBox face_boxes = 2;</code>
   */
  @Override
  public int getFaceBoxesCount() {
    return faceBoxes_.size();
  }
  /**
   * <pre>
   * 检测框
   * </pre>
   *
   * <code>repeated .FaceBox face_boxes = 2;</code>
   */
  @Override
  public FaceBox getFaceBoxes(int index) {
    return faceBoxes_.get(index);
  }
  /**
   * <pre>
   * 检测框
   * </pre>
   *
   * <code>repeated .FaceBox face_boxes = 2;</code>
   */
  @Override
  public FaceBoxOrBuilder getFaceBoxesOrBuilder(
      int index) {
    return faceBoxes_.get(index);
  }

  public static final int PERSON_BOXES_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<PersonBox> personBoxes_;
  /**
   * <code>repeated .PersonBox person_boxes = 3;</code>
   */
  @Override
  public java.util.List<PersonBox> getPersonBoxesList() {
    return personBoxes_;
  }
  /**
   * <code>repeated .PersonBox person_boxes = 3;</code>
   */
  @Override
  public java.util.List<? extends PersonBoxOrBuilder>
      getPersonBoxesOrBuilderList() {
    return personBoxes_;
  }
  /**
   * <code>repeated .PersonBox person_boxes = 3;</code>
   */
  @Override
  public int getPersonBoxesCount() {
    return personBoxes_.size();
  }
  /**
   * <code>repeated .PersonBox person_boxes = 3;</code>
   */
  @Override
  public PersonBox getPersonBoxes(int index) {
    return personBoxes_.get(index);
  }
  /**
   * <code>repeated .PersonBox person_boxes = 3;</code>
   */
  @Override
  public PersonBoxOrBuilder getPersonBoxesOrBuilder(
      int index) {
    return personBoxes_.get(index);
  }

  public static final int DATA_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile Object data_ = "";
  /**
   * <pre>
   * 算法返回数据
   * </pre>
   *
   * <code>string data = 4;</code>
   * @return The data.
   */
  @Override
  public String getData() {
    Object ref = data_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      data_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 算法返回数据
   * </pre>
   *
   * <code>string data = 4;</code>
   * @return The bytes for data.
   */
  @Override
  public com.google.protobuf.ByteString
      getDataBytes() {
    Object ref = data_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      data_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMAGE_DATA_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString imageData_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes image_data = 5;</code>
   * @return The imageData.
   */
  @Override
  public com.google.protobuf.ByteString getImageData() {
    return imageData_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (timestamp_ != 0L) {
      output.writeInt64(1, timestamp_);
    }
    for (int i = 0; i < faceBoxes_.size(); i++) {
      output.writeMessage(2, faceBoxes_.get(i));
    }
    for (int i = 0; i < personBoxes_.size(); i++) {
      output.writeMessage(3, personBoxes_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(data_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, data_);
    }
    if (!imageData_.isEmpty()) {
      output.writeBytes(5, imageData_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, timestamp_);
    }
    for (int i = 0; i < faceBoxes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, faceBoxes_.get(i));
    }
    for (int i = 0; i < personBoxes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, personBoxes_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(data_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, data_);
    }
    if (!imageData_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, imageData_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof AnalysisResult)) {
      return super.equals(obj);
    }
    AnalysisResult other = (AnalysisResult) obj;

    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getFaceBoxesList()
        .equals(other.getFaceBoxesList())) return false;
    if (!getPersonBoxesList()
        .equals(other.getPersonBoxesList())) return false;
    if (!getData()
        .equals(other.getData())) return false;
    if (!getImageData()
        .equals(other.getImageData())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    if (getFaceBoxesCount() > 0) {
      hash = (37 * hash) + FACE_BOXES_FIELD_NUMBER;
      hash = (53 * hash) + getFaceBoxesList().hashCode();
    }
    if (getPersonBoxesCount() > 0) {
      hash = (37 * hash) + PERSON_BOXES_FIELD_NUMBER;
      hash = (53 * hash) + getPersonBoxesList().hashCode();
    }
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (37 * hash) + IMAGE_DATA_FIELD_NUMBER;
    hash = (53 * hash) + getImageData().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static AnalysisResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AnalysisResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AnalysisResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AnalysisResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AnalysisResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AnalysisResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AnalysisResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static AnalysisResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static AnalysisResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static AnalysisResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static AnalysisResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static AnalysisResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(AnalysisResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AnalysisResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AnalysisResult)
      AnalysisResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return VideoProto.internal_static_AnalysisResult_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return VideoProto.internal_static_AnalysisResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AnalysisResult.class, Builder.class);
    }

    // Construct using com.saigou.grpc.AnalysisResult.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      timestamp_ = 0L;
      if (faceBoxesBuilder_ == null) {
        faceBoxes_ = java.util.Collections.emptyList();
      } else {
        faceBoxes_ = null;
        faceBoxesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (personBoxesBuilder_ == null) {
        personBoxes_ = java.util.Collections.emptyList();
      } else {
        personBoxes_ = null;
        personBoxesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      data_ = "";
      imageData_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return VideoProto.internal_static_AnalysisResult_descriptor;
    }

    @Override
    public AnalysisResult getDefaultInstanceForType() {
      return AnalysisResult.getDefaultInstance();
    }

    @Override
    public AnalysisResult build() {
      AnalysisResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public AnalysisResult buildPartial() {
      AnalysisResult result = new AnalysisResult(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(AnalysisResult result) {
      if (faceBoxesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          faceBoxes_ = java.util.Collections.unmodifiableList(faceBoxes_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.faceBoxes_ = faceBoxes_;
      } else {
        result.faceBoxes_ = faceBoxesBuilder_.build();
      }
      if (personBoxesBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          personBoxes_ = java.util.Collections.unmodifiableList(personBoxes_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.personBoxes_ = personBoxes_;
      } else {
        result.personBoxes_ = personBoxesBuilder_.build();
      }
    }

    private void buildPartial0(AnalysisResult result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.timestamp_ = timestamp_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.data_ = data_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.imageData_ = imageData_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof AnalysisResult) {
        return mergeFrom((AnalysisResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(AnalysisResult other) {
      if (other == AnalysisResult.getDefaultInstance()) return this;
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (faceBoxesBuilder_ == null) {
        if (!other.faceBoxes_.isEmpty()) {
          if (faceBoxes_.isEmpty()) {
            faceBoxes_ = other.faceBoxes_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureFaceBoxesIsMutable();
            faceBoxes_.addAll(other.faceBoxes_);
          }
          onChanged();
        }
      } else {
        if (!other.faceBoxes_.isEmpty()) {
          if (faceBoxesBuilder_.isEmpty()) {
            faceBoxesBuilder_.dispose();
            faceBoxesBuilder_ = null;
            faceBoxes_ = other.faceBoxes_;
            bitField0_ = (bitField0_ & ~0x00000002);
            faceBoxesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getFaceBoxesFieldBuilder() : null;
          } else {
            faceBoxesBuilder_.addAllMessages(other.faceBoxes_);
          }
        }
      }
      if (personBoxesBuilder_ == null) {
        if (!other.personBoxes_.isEmpty()) {
          if (personBoxes_.isEmpty()) {
            personBoxes_ = other.personBoxes_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePersonBoxesIsMutable();
            personBoxes_.addAll(other.personBoxes_);
          }
          onChanged();
        }
      } else {
        if (!other.personBoxes_.isEmpty()) {
          if (personBoxesBuilder_.isEmpty()) {
            personBoxesBuilder_.dispose();
            personBoxesBuilder_ = null;
            personBoxes_ = other.personBoxes_;
            bitField0_ = (bitField0_ & ~0x00000004);
            personBoxesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getPersonBoxesFieldBuilder() : null;
          } else {
            personBoxesBuilder_.addAllMessages(other.personBoxes_);
          }
        }
      }
      if (!other.getData().isEmpty()) {
        data_ = other.data_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getImageData() != com.google.protobuf.ByteString.EMPTY) {
        setImageData(other.getImageData());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              FaceBox m =
                  input.readMessage(
                      FaceBox.parser(),
                      extensionRegistry);
              if (faceBoxesBuilder_ == null) {
                ensureFaceBoxesIsMutable();
                faceBoxes_.add(m);
              } else {
                faceBoxesBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              PersonBox m =
                  input.readMessage(
                      PersonBox.parser(),
                      extensionRegistry);
              if (personBoxesBuilder_ == null) {
                ensurePersonBoxesIsMutable();
                personBoxes_.add(m);
              } else {
                personBoxesBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              data_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              imageData_ = input.readBytes();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long timestamp_ ;
    /**
     * <pre>
     * 时间戳（毫秒）
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    @Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * 时间戳（毫秒）
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 时间戳（毫秒）
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000001);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<FaceBox> faceBoxes_ =
      java.util.Collections.emptyList();
    private void ensureFaceBoxesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        faceBoxes_ = new java.util.ArrayList<FaceBox>(faceBoxes_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        FaceBox, FaceBox.Builder, FaceBoxOrBuilder> faceBoxesBuilder_;

    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .FaceBox face_boxes = 2;</code>
     */
    public java.util.List<FaceBox> getFaceBoxesList() {
      if (faceBoxesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(faceBoxes_);
      } else {
        return faceBoxesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .FaceBox face_boxes = 2;</code>
     */
    public int getFaceBoxesCount() {
      if (faceBoxesBuilder_ == null) {
        return faceBoxes_.size();
      } else {
        return faceBoxesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .FaceBox face_boxes = 2;</code>
     */
    public FaceBox getFaceBoxes(int index) {
      if (faceBoxesBuilder_ == null) {
        return faceBoxes_.get(index);
      } else {
        return faceBoxesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .FaceBox face_boxes = 2;</code>
     */
    public Builder setFaceBoxes(
        int index, FaceBox value) {
      if (faceBoxesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFaceBoxesIsMutable();
        faceBoxes_.set(index, value);
        onChanged();
      } else {
        faceBoxesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .FaceBox face_boxes = 2;</code>
     */
    public Builder setFaceBoxes(
        int index, FaceBox.Builder builderForValue) {
      if (faceBoxesBuilder_ == null) {
        ensureFaceBoxesIsMutable();
        faceBoxes_.set(index, builderForValue.build());
        onChanged();
      } else {
        faceBoxesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .FaceBox face_boxes = 2;</code>
     */
    public Builder addFaceBoxes(FaceBox value) {
      if (faceBoxesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFaceBoxesIsMutable();
        faceBoxes_.add(value);
        onChanged();
      } else {
        faceBoxesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .FaceBox face_boxes = 2;</code>
     */
    public Builder addFaceBoxes(
        int index, FaceBox value) {
      if (faceBoxesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFaceBoxesIsMutable();
        faceBoxes_.add(index, value);
        onChanged();
      } else {
        faceBoxesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .FaceBox face_boxes = 2;</code>
     */
    public Builder addFaceBoxes(
        FaceBox.Builder builderForValue) {
      if (faceBoxesBuilder_ == null) {
        ensureFaceBoxesIsMutable();
        faceBoxes_.add(builderForValue.build());
        onChanged();
      } else {
        faceBoxesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .FaceBox face_boxes = 2;</code>
     */
    public Builder addFaceBoxes(
        int index, FaceBox.Builder builderForValue) {
      if (faceBoxesBuilder_ == null) {
        ensureFaceBoxesIsMutable();
        faceBoxes_.add(index, builderForValue.build());
        onChanged();
      } else {
        faceBoxesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .FaceBox face_boxes = 2;</code>
     */
    public Builder addAllFaceBoxes(
        Iterable<? extends FaceBox> values) {
      if (faceBoxesBuilder_ == null) {
        ensureFaceBoxesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, faceBoxes_);
        onChanged();
      } else {
        faceBoxesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .FaceBox face_boxes = 2;</code>
     */
    public Builder clearFaceBoxes() {
      if (faceBoxesBuilder_ == null) {
        faceBoxes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        faceBoxesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .FaceBox face_boxes = 2;</code>
     */
    public Builder removeFaceBoxes(int index) {
      if (faceBoxesBuilder_ == null) {
        ensureFaceBoxesIsMutable();
        faceBoxes_.remove(index);
        onChanged();
      } else {
        faceBoxesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .FaceBox face_boxes = 2;</code>
     */
    public FaceBox.Builder getFaceBoxesBuilder(
        int index) {
      return getFaceBoxesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .FaceBox face_boxes = 2;</code>
     */
    public FaceBoxOrBuilder getFaceBoxesOrBuilder(
        int index) {
      if (faceBoxesBuilder_ == null) {
        return faceBoxes_.get(index);  } else {
        return faceBoxesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .FaceBox face_boxes = 2;</code>
     */
    public java.util.List<? extends FaceBoxOrBuilder>
         getFaceBoxesOrBuilderList() {
      if (faceBoxesBuilder_ != null) {
        return faceBoxesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(faceBoxes_);
      }
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .FaceBox face_boxes = 2;</code>
     */
    public FaceBox.Builder addFaceBoxesBuilder() {
      return getFaceBoxesFieldBuilder().addBuilder(
          FaceBox.getDefaultInstance());
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .FaceBox face_boxes = 2;</code>
     */
    public FaceBox.Builder addFaceBoxesBuilder(
        int index) {
      return getFaceBoxesFieldBuilder().addBuilder(
          index, FaceBox.getDefaultInstance());
    }
    /**
     * <pre>
     * 检测框
     * </pre>
     *
     * <code>repeated .FaceBox face_boxes = 2;</code>
     */
    public java.util.List<FaceBox.Builder>
         getFaceBoxesBuilderList() {
      return getFaceBoxesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        FaceBox, FaceBox.Builder, FaceBoxOrBuilder>
        getFaceBoxesFieldBuilder() {
      if (faceBoxesBuilder_ == null) {
        faceBoxesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            FaceBox, FaceBox.Builder, FaceBoxOrBuilder>(
                faceBoxes_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        faceBoxes_ = null;
      }
      return faceBoxesBuilder_;
    }

    private java.util.List<PersonBox> personBoxes_ =
      java.util.Collections.emptyList();
    private void ensurePersonBoxesIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        personBoxes_ = new java.util.ArrayList<PersonBox>(personBoxes_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        PersonBox, PersonBox.Builder, PersonBoxOrBuilder> personBoxesBuilder_;

    /**
     * <code>repeated .PersonBox person_boxes = 3;</code>
     */
    public java.util.List<PersonBox> getPersonBoxesList() {
      if (personBoxesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(personBoxes_);
      } else {
        return personBoxesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .PersonBox person_boxes = 3;</code>
     */
    public int getPersonBoxesCount() {
      if (personBoxesBuilder_ == null) {
        return personBoxes_.size();
      } else {
        return personBoxesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .PersonBox person_boxes = 3;</code>
     */
    public PersonBox getPersonBoxes(int index) {
      if (personBoxesBuilder_ == null) {
        return personBoxes_.get(index);
      } else {
        return personBoxesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .PersonBox person_boxes = 3;</code>
     */
    public Builder setPersonBoxes(
        int index, PersonBox value) {
      if (personBoxesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePersonBoxesIsMutable();
        personBoxes_.set(index, value);
        onChanged();
      } else {
        personBoxesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PersonBox person_boxes = 3;</code>
     */
    public Builder setPersonBoxes(
        int index, PersonBox.Builder builderForValue) {
      if (personBoxesBuilder_ == null) {
        ensurePersonBoxesIsMutable();
        personBoxes_.set(index, builderForValue.build());
        onChanged();
      } else {
        personBoxesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PersonBox person_boxes = 3;</code>
     */
    public Builder addPersonBoxes(PersonBox value) {
      if (personBoxesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePersonBoxesIsMutable();
        personBoxes_.add(value);
        onChanged();
      } else {
        personBoxesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .PersonBox person_boxes = 3;</code>
     */
    public Builder addPersonBoxes(
        int index, PersonBox value) {
      if (personBoxesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePersonBoxesIsMutable();
        personBoxes_.add(index, value);
        onChanged();
      } else {
        personBoxesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PersonBox person_boxes = 3;</code>
     */
    public Builder addPersonBoxes(
        PersonBox.Builder builderForValue) {
      if (personBoxesBuilder_ == null) {
        ensurePersonBoxesIsMutable();
        personBoxes_.add(builderForValue.build());
        onChanged();
      } else {
        personBoxesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PersonBox person_boxes = 3;</code>
     */
    public Builder addPersonBoxes(
        int index, PersonBox.Builder builderForValue) {
      if (personBoxesBuilder_ == null) {
        ensurePersonBoxesIsMutable();
        personBoxes_.add(index, builderForValue.build());
        onChanged();
      } else {
        personBoxesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PersonBox person_boxes = 3;</code>
     */
    public Builder addAllPersonBoxes(
        Iterable<? extends PersonBox> values) {
      if (personBoxesBuilder_ == null) {
        ensurePersonBoxesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, personBoxes_);
        onChanged();
      } else {
        personBoxesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .PersonBox person_boxes = 3;</code>
     */
    public Builder clearPersonBoxes() {
      if (personBoxesBuilder_ == null) {
        personBoxes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        personBoxesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .PersonBox person_boxes = 3;</code>
     */
    public Builder removePersonBoxes(int index) {
      if (personBoxesBuilder_ == null) {
        ensurePersonBoxesIsMutable();
        personBoxes_.remove(index);
        onChanged();
      } else {
        personBoxesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .PersonBox person_boxes = 3;</code>
     */
    public PersonBox.Builder getPersonBoxesBuilder(
        int index) {
      return getPersonBoxesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .PersonBox person_boxes = 3;</code>
     */
    public PersonBoxOrBuilder getPersonBoxesOrBuilder(
        int index) {
      if (personBoxesBuilder_ == null) {
        return personBoxes_.get(index);  } else {
        return personBoxesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .PersonBox person_boxes = 3;</code>
     */
    public java.util.List<? extends PersonBoxOrBuilder>
         getPersonBoxesOrBuilderList() {
      if (personBoxesBuilder_ != null) {
        return personBoxesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(personBoxes_);
      }
    }
    /**
     * <code>repeated .PersonBox person_boxes = 3;</code>
     */
    public PersonBox.Builder addPersonBoxesBuilder() {
      return getPersonBoxesFieldBuilder().addBuilder(
          PersonBox.getDefaultInstance());
    }
    /**
     * <code>repeated .PersonBox person_boxes = 3;</code>
     */
    public PersonBox.Builder addPersonBoxesBuilder(
        int index) {
      return getPersonBoxesFieldBuilder().addBuilder(
          index, PersonBox.getDefaultInstance());
    }
    /**
     * <code>repeated .PersonBox person_boxes = 3;</code>
     */
    public java.util.List<PersonBox.Builder>
         getPersonBoxesBuilderList() {
      return getPersonBoxesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        PersonBox, PersonBox.Builder, PersonBoxOrBuilder>
        getPersonBoxesFieldBuilder() {
      if (personBoxesBuilder_ == null) {
        personBoxesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            PersonBox, PersonBox.Builder, PersonBoxOrBuilder>(
                personBoxes_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        personBoxes_ = null;
      }
      return personBoxesBuilder_;
    }

    private Object data_ = "";
    /**
     * <pre>
     * 算法返回数据
     * </pre>
     *
     * <code>string data = 4;</code>
     * @return The data.
     */
    public String getData() {
      Object ref = data_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        data_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 算法返回数据
     * </pre>
     *
     * <code>string data = 4;</code>
     * @return The bytes for data.
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 算法返回数据
     * </pre>
     *
     * <code>string data = 4;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      data_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 算法返回数据
     * </pre>
     *
     * <code>string data = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      data_ = getDefaultInstance().getData();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 算法返回数据
     * </pre>
     *
     * <code>string data = 4;</code>
     * @param value The bytes for data to set.
     * @return This builder for chaining.
     */
    public Builder setDataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      data_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString imageData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes image_data = 5;</code>
     * @return The imageData.
     */
    @Override
    public com.google.protobuf.ByteString getImageData() {
      return imageData_;
    }
    /**
     * <code>bytes image_data = 5;</code>
     * @param value The imageData to set.
     * @return This builder for chaining.
     */
    public Builder setImageData(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      imageData_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>bytes image_data = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearImageData() {
      bitField0_ = (bitField0_ & ~0x00000010);
      imageData_ = getDefaultInstance().getImageData();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:AnalysisResult)
  }

  // @@protoc_insertion_point(class_scope:AnalysisResult)
  private static final AnalysisResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new AnalysisResult();
  }

  public static AnalysisResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AnalysisResult>
      PARSER = new com.google.protobuf.AbstractParser<AnalysisResult>() {
    @Override
    public AnalysisResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AnalysisResult> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<AnalysisResult> getParserForType() {
    return PARSER;
  }

  @Override
  public AnalysisResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

