// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: video.proto
// Protobuf Java Version: 4.28.0

package com.saigou.grpc;

public interface AnalysisResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AnalysisResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 时间戳（毫秒）
   * </pre>
   *
   * <code>int64 timestamp = 1;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <pre>
   * 检测框
   * </pre>
   *
   * <code>repeated .FaceBox face_boxes = 2;</code>
   */
  java.util.List<FaceBox>
      getFaceBoxesList();
  /**
   * <pre>
   * 检测框
   * </pre>
   *
   * <code>repeated .FaceBox face_boxes = 2;</code>
   */
  FaceBox getFaceBoxes(int index);
  /**
   * <pre>
   * 检测框
   * </pre>
   *
   * <code>repeated .FaceBox face_boxes = 2;</code>
   */
  int getFaceBoxesCount();
  /**
   * <pre>
   * 检测框
   * </pre>
   *
   * <code>repeated .FaceBox face_boxes = 2;</code>
   */
  java.util.List<? extends FaceBoxOrBuilder>
      getFaceBoxesOrBuilderList();
  /**
   * <pre>
   * 检测框
   * </pre>
   *
   * <code>repeated .FaceBox face_boxes = 2;</code>
   */
  FaceBoxOrBuilder getFaceBoxesOrBuilder(
      int index);

  /**
   * <code>repeated .PersonBox person_boxes = 3;</code>
   */
  java.util.List<PersonBox>
      getPersonBoxesList();
  /**
   * <code>repeated .PersonBox person_boxes = 3;</code>
   */
  PersonBox getPersonBoxes(int index);
  /**
   * <code>repeated .PersonBox person_boxes = 3;</code>
   */
  int getPersonBoxesCount();
  /**
   * <code>repeated .PersonBox person_boxes = 3;</code>
   */
  java.util.List<? extends PersonBoxOrBuilder>
      getPersonBoxesOrBuilderList();
  /**
   * <code>repeated .PersonBox person_boxes = 3;</code>
   */
  PersonBoxOrBuilder getPersonBoxesOrBuilder(
      int index);

  /**
   * <pre>
   * 算法返回数据
   * </pre>
   *
   * <code>string data = 4;</code>
   * @return The data.
   */
  String getData();
  /**
   * <pre>
   * 算法返回数据
   * </pre>
   *
   * <code>string data = 4;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();

  /**
   * <code>bytes image_data = 5;</code>
   * @return The imageData.
   */
  com.google.protobuf.ByteString getImageData();
}
