// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: video.proto
// Protobuf Java Version: 4.28.0

package com.saigou.grpc;

public interface AnalysisResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AnalysisResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 时间戳（毫秒）
   * </pre>
   *
   * <code>int64 timestamp = 1;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <pre>
   * 检测框
   * </pre>
   *
   * <code>repeated .BoundingBox boxes = 2;</code>
   */
  java.util.List<BoundingBox>
      getBoxesList();
  /**
   * <pre>
   * 检测框
   * </pre>
   *
   * <code>repeated .BoundingBox boxes = 2;</code>
   */
  BoundingBox getBoxes(int index);
  /**
   * <pre>
   * 检测框
   * </pre>
   *
   * <code>repeated .BoundingBox boxes = 2;</code>
   */
  int getBoxesCount();
  /**
   * <pre>
   * 检测框
   * </pre>
   *
   * <code>repeated .BoundingBox boxes = 2;</code>
   */
  java.util.List<? extends BoundingBoxOrBuilder>
      getBoxesOrBuilderList();
  /**
   * <pre>
   * 检测框
   * </pre>
   *
   * <code>repeated .BoundingBox boxes = 2;</code>
   */
  BoundingBoxOrBuilder getBoxesOrBuilder(
      int index);

  /**
   * <pre>
   * 算法返回数据
   * </pre>
   *
   * <code>string data = 3;</code>
   * @return The data.
   */
  String getData();
  /**
   * <pre>
   * 算法返回数据
   * </pre>
   *
   * <code>string data = 3;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();

  /**
   * <code>bytes image_data = 4;</code>
   * @return The imageData.
   */
  com.google.protobuf.ByteString getImageData();
}
