// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: video.proto
// Protobuf Java Version: 4.28.0

package com.saigou.grpc;

/**
 * Protobuf type {@code BoundingBox}
 */
public final class BoundingBox extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:BoundingBox)
        BoundingBoxOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 0,
      /* suffix= */ "",
      BoundingBox.class.getName());
  }
  // Use BoundingBox.newBuilder() to construct.
  private BoundingBox(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BoundingBox() {
    label_ = "";
    trackId_ = "";
    data_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return VideoProto.internal_static_BoundingBox_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return VideoProto.internal_static_BoundingBox_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            BoundingBox.class, BoundingBox.Builder.class);
  }

  public static final int LABEL_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object label_ = "";
  /**
   * <pre>
   * 类别标签
   * </pre>
   *
   * <code>string label = 1;</code>
   * @return The label.
   */
  @Override
  public String getLabel() {
    Object ref = label_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      label_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 类别标签
   * </pre>
   *
   * <code>string label = 1;</code>
   * @return The bytes for label.
   */
  @Override
  public com.google.protobuf.ByteString
      getLabelBytes() {
    Object ref = label_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      label_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int X_FIELD_NUMBER = 2;
  private long x_ = 0L;
  /**
   * <pre>
   * 左上角X坐标
   * </pre>
   *
   * <code>int64 x = 2;</code>
   * @return The x.
   */
  @Override
  public long getX() {
    return x_;
  }

  public static final int Y_FIELD_NUMBER = 3;
  private long y_ = 0L;
  /**
   * <pre>
   * 左上角Y坐标
   * </pre>
   *
   * <code>int64 y = 3;</code>
   * @return The y.
   */
  @Override
  public long getY() {
    return y_;
  }

  public static final int WIDTH_FIELD_NUMBER = 4;
  private long width_ = 0L;
  /**
   * <pre>
   * 框宽度
   * </pre>
   *
   * <code>int64 width = 4;</code>
   * @return The width.
   */
  @Override
  public long getWidth() {
    return width_;
  }

  public static final int HEIGHT_FIELD_NUMBER = 5;
  private long height_ = 0L;
  /**
   * <pre>
   * 框高度
   * </pre>
   *
   * <code>int64 height = 5;</code>
   * @return The height.
   */
  @Override
  public long getHeight() {
    return height_;
  }

  public static final int SCORE_FIELD_NUMBER = 6;
  private float score_ = 0F;
  /**
   * <pre>
   * 置信度
   * </pre>
   *
   * <code>float score = 6;</code>
   * @return The score.
   */
  @Override
  public float getScore() {
    return score_;
  }

  public static final int TRACK_ID_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile Object trackId_ = "";
  /**
   * <pre>
   * 轨迹ID
   * </pre>
   *
   * <code>string track_id = 7;</code>
   * @return The trackId.
   */
  @Override
  public String getTrackId() {
    Object ref = trackId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      trackId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 轨迹ID
   * </pre>
   *
   * <code>string track_id = 7;</code>
   * @return The bytes for trackId.
   */
  @Override
  public com.google.protobuf.ByteString
      getTrackIdBytes() {
    Object ref = trackId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      trackId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile Object data_ = "";
  /**
   * <pre>
   * 额外数据(JSON格式)
   * </pre>
   *
   * <code>string data = 8;</code>
   * @return The data.
   */
  @Override
  public String getData() {
    Object ref = data_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      data_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 额外数据(JSON格式)
   * </pre>
   *
   * <code>string data = 8;</code>
   * @return The bytes for data.
   */
  @Override
  public com.google.protobuf.ByteString
      getDataBytes() {
    Object ref = data_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      data_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(label_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, label_);
    }
    if (x_ != 0L) {
      output.writeInt64(2, x_);
    }
    if (y_ != 0L) {
      output.writeInt64(3, y_);
    }
    if (width_ != 0L) {
      output.writeInt64(4, width_);
    }
    if (height_ != 0L) {
      output.writeInt64(5, height_);
    }
    if (Float.floatToRawIntBits(score_) != 0) {
      output.writeFloat(6, score_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(trackId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, trackId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(data_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, data_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(label_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, label_);
    }
    if (x_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, x_);
    }
    if (y_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, y_);
    }
    if (width_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, width_);
    }
    if (height_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, height_);
    }
    if (Float.floatToRawIntBits(score_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(6, score_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(trackId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, trackId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(data_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, data_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof BoundingBox)) {
      return super.equals(obj);
    }
    BoundingBox other = (BoundingBox) obj;

    if (!getLabel()
        .equals(other.getLabel())) return false;
    if (getX()
        != other.getX()) return false;
    if (getY()
        != other.getY()) return false;
    if (getWidth()
        != other.getWidth()) return false;
    if (getHeight()
        != other.getHeight()) return false;
    if (Float.floatToIntBits(getScore())
        != Float.floatToIntBits(
            other.getScore())) return false;
    if (!getTrackId()
        .equals(other.getTrackId())) return false;
    if (!getData()
        .equals(other.getData())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LABEL_FIELD_NUMBER;
    hash = (53 * hash) + getLabel().hashCode();
    hash = (37 * hash) + X_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getX());
    hash = (37 * hash) + Y_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getY());
    hash = (37 * hash) + WIDTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getWidth());
    hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getHeight());
    hash = (37 * hash) + SCORE_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getScore());
    hash = (37 * hash) + TRACK_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTrackId().hashCode();
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static BoundingBox parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BoundingBox parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BoundingBox parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BoundingBox parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BoundingBox parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BoundingBox parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BoundingBox parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static BoundingBox parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static BoundingBox parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static BoundingBox parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static BoundingBox parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static BoundingBox parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(BoundingBox prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code BoundingBox}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BoundingBox)
          BoundingBoxOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return VideoProto.internal_static_BoundingBox_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return VideoProto.internal_static_BoundingBox_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BoundingBox.class, BoundingBox.Builder.class);
    }

    // Construct using com.saigou.grpc.BoundingBox.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      label_ = "";
      x_ = 0L;
      y_ = 0L;
      width_ = 0L;
      height_ = 0L;
      score_ = 0F;
      trackId_ = "";
      data_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return VideoProto.internal_static_BoundingBox_descriptor;
    }

    @Override
    public BoundingBox getDefaultInstanceForType() {
      return BoundingBox.getDefaultInstance();
    }

    @Override
    public BoundingBox build() {
      BoundingBox result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public BoundingBox buildPartial() {
      BoundingBox result = new BoundingBox(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(BoundingBox result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.label_ = label_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.x_ = x_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.y_ = y_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.width_ = width_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.height_ = height_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.score_ = score_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.trackId_ = trackId_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.data_ = data_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof BoundingBox) {
        return mergeFrom((BoundingBox)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(BoundingBox other) {
      if (other == BoundingBox.getDefaultInstance()) return this;
      if (!other.getLabel().isEmpty()) {
        label_ = other.label_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getX() != 0L) {
        setX(other.getX());
      }
      if (other.getY() != 0L) {
        setY(other.getY());
      }
      if (other.getWidth() != 0L) {
        setWidth(other.getWidth());
      }
      if (other.getHeight() != 0L) {
        setHeight(other.getHeight());
      }
      if (other.getScore() != 0F) {
        setScore(other.getScore());
      }
      if (!other.getTrackId().isEmpty()) {
        trackId_ = other.trackId_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getData().isEmpty()) {
        data_ = other.data_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              label_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              x_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              y_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              width_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              height_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 53: {
              score_ = input.readFloat();
              bitField0_ |= 0x00000020;
              break;
            } // case 53
            case 58: {
              trackId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              data_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object label_ = "";
    /**
     * <pre>
     * 类别标签
     * </pre>
     *
     * <code>string label = 1;</code>
     * @return The label.
     */
    public String getLabel() {
      Object ref = label_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        label_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 类别标签
     * </pre>
     *
     * <code>string label = 1;</code>
     * @return The bytes for label.
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      Object ref = label_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 类别标签
     * </pre>
     *
     * <code>string label = 1;</code>
     * @param value The label to set.
     * @return This builder for chaining.
     */
    public Builder setLabel(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      label_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 类别标签
     * </pre>
     *
     * <code>string label = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLabel() {
      label_ = getDefaultInstance().getLabel();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 类别标签
     * </pre>
     *
     * <code>string label = 1;</code>
     * @param value The bytes for label to set.
     * @return This builder for chaining.
     */
    public Builder setLabelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      label_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long x_ ;
    /**
     * <pre>
     * 左上角X坐标
     * </pre>
     *
     * <code>int64 x = 2;</code>
     * @return The x.
     */
    @Override
    public long getX() {
      return x_;
    }
    /**
     * <pre>
     * 左上角X坐标
     * </pre>
     *
     * <code>int64 x = 2;</code>
     * @param value The x to set.
     * @return This builder for chaining.
     */
    public Builder setX(long value) {

      x_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 左上角X坐标
     * </pre>
     *
     * <code>int64 x = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearX() {
      bitField0_ = (bitField0_ & ~0x00000002);
      x_ = 0L;
      onChanged();
      return this;
    }

    private long y_ ;
    /**
     * <pre>
     * 左上角Y坐标
     * </pre>
     *
     * <code>int64 y = 3;</code>
     * @return The y.
     */
    @Override
    public long getY() {
      return y_;
    }
    /**
     * <pre>
     * 左上角Y坐标
     * </pre>
     *
     * <code>int64 y = 3;</code>
     * @param value The y to set.
     * @return This builder for chaining.
     */
    public Builder setY(long value) {

      y_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 左上角Y坐标
     * </pre>
     *
     * <code>int64 y = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearY() {
      bitField0_ = (bitField0_ & ~0x00000004);
      y_ = 0L;
      onChanged();
      return this;
    }

    private long width_ ;
    /**
     * <pre>
     * 框宽度
     * </pre>
     *
     * <code>int64 width = 4;</code>
     * @return The width.
     */
    @Override
    public long getWidth() {
      return width_;
    }
    /**
     * <pre>
     * 框宽度
     * </pre>
     *
     * <code>int64 width = 4;</code>
     * @param value The width to set.
     * @return This builder for chaining.
     */
    public Builder setWidth(long value) {

      width_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 框宽度
     * </pre>
     *
     * <code>int64 width = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearWidth() {
      bitField0_ = (bitField0_ & ~0x00000008);
      width_ = 0L;
      onChanged();
      return this;
    }

    private long height_ ;
    /**
     * <pre>
     * 框高度
     * </pre>
     *
     * <code>int64 height = 5;</code>
     * @return The height.
     */
    @Override
    public long getHeight() {
      return height_;
    }
    /**
     * <pre>
     * 框高度
     * </pre>
     *
     * <code>int64 height = 5;</code>
     * @param value The height to set.
     * @return This builder for chaining.
     */
    public Builder setHeight(long value) {

      height_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 框高度
     * </pre>
     *
     * <code>int64 height = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeight() {
      bitField0_ = (bitField0_ & ~0x00000010);
      height_ = 0L;
      onChanged();
      return this;
    }

    private float score_ ;
    /**
     * <pre>
     * 置信度
     * </pre>
     *
     * <code>float score = 6;</code>
     * @return The score.
     */
    @Override
    public float getScore() {
      return score_;
    }
    /**
     * <pre>
     * 置信度
     * </pre>
     *
     * <code>float score = 6;</code>
     * @param value The score to set.
     * @return This builder for chaining.
     */
    public Builder setScore(float value) {

      score_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 置信度
     * </pre>
     *
     * <code>float score = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearScore() {
      bitField0_ = (bitField0_ & ~0x00000020);
      score_ = 0F;
      onChanged();
      return this;
    }

    private Object trackId_ = "";
    /**
     * <pre>
     * 轨迹ID
     * </pre>
     *
     * <code>string track_id = 7;</code>
     * @return The trackId.
     */
    public String getTrackId() {
      Object ref = trackId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        trackId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 轨迹ID
     * </pre>
     *
     * <code>string track_id = 7;</code>
     * @return The bytes for trackId.
     */
    public com.google.protobuf.ByteString
        getTrackIdBytes() {
      Object ref = trackId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        trackId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 轨迹ID
     * </pre>
     *
     * <code>string track_id = 7;</code>
     * @param value The trackId to set.
     * @return This builder for chaining.
     */
    public Builder setTrackId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      trackId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 轨迹ID
     * </pre>
     *
     * <code>string track_id = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrackId() {
      trackId_ = getDefaultInstance().getTrackId();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 轨迹ID
     * </pre>
     *
     * <code>string track_id = 7;</code>
     * @param value The bytes for trackId to set.
     * @return This builder for chaining.
     */
    public Builder setTrackIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      trackId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private Object data_ = "";
    /**
     * <pre>
     * 额外数据(JSON格式)
     * </pre>
     *
     * <code>string data = 8;</code>
     * @return The data.
     */
    public String getData() {
      Object ref = data_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        data_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 额外数据(JSON格式)
     * </pre>
     *
     * <code>string data = 8;</code>
     * @return The bytes for data.
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 额外数据(JSON格式)
     * </pre>
     *
     * <code>string data = 8;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      data_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 额外数据(JSON格式)
     * </pre>
     *
     * <code>string data = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      data_ = getDefaultInstance().getData();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 额外数据(JSON格式)
     * </pre>
     *
     * <code>string data = 8;</code>
     * @param value The bytes for data to set.
     * @return This builder for chaining.
     */
    public Builder setDataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      data_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:BoundingBox)
  }

  // @@protoc_insertion_point(class_scope:BoundingBox)
  private static final BoundingBox DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new BoundingBox();
  }

  public static BoundingBox getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BoundingBox>
      PARSER = new com.google.protobuf.AbstractParser<BoundingBox>() {
    @Override
    public BoundingBox parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BoundingBox> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<BoundingBox> getParserForType() {
    return PARSER;
  }

  @Override
  public BoundingBox getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

