// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: video.proto
// Protobuf Java Version: 4.28.0

package com.saigou.grpc;

public interface BoundingBoxOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BoundingBox)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 类别标签
   * </pre>
   *
   * <code>string label = 1;</code>
   * @return The label.
   */
  String getLabel();
  /**
   * <pre>
   * 类别标签
   * </pre>
   *
   * <code>string label = 1;</code>
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <pre>
   * 左上角X坐标
   * </pre>
   *
   * <code>int64 x = 2;</code>
   * @return The x.
   */
  long getX();

  /**
   * <pre>
   * 左上角Y坐标
   * </pre>
   *
   * <code>int64 y = 3;</code>
   * @return The y.
   */
  long getY();

  /**
   * <pre>
   * 框宽度
   * </pre>
   *
   * <code>int64 width = 4;</code>
   * @return The width.
   */
  long getWidth();

  /**
   * <pre>
   * 框高度
   * </pre>
   *
   * <code>int64 height = 5;</code>
   * @return The height.
   */
  long getHeight();

  /**
   * <pre>
   * 置信度
   * </pre>
   *
   * <code>float score = 6;</code>
   * @return The score.
   */
  float getScore();

  /**
   * <pre>
   * 轨迹ID
   * </pre>
   *
   * <code>string track_id = 7;</code>
   * @return The trackId.
   */
  String getTrackId();
  /**
   * <pre>
   * 轨迹ID
   * </pre>
   *
   * <code>string track_id = 7;</code>
   * @return The bytes for trackId.
   */
  com.google.protobuf.ByteString
      getTrackIdBytes();

  /**
   * <pre>
   * 额外数据(JSON格式)
   * </pre>
   *
   * <code>string data = 8;</code>
   * @return The data.
   */
  String getData();
  /**
   * <pre>
   * 额外数据(JSON格式)
   * </pre>
   *
   * <code>string data = 8;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
