// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: video.proto
// Protobuf Java Version: 4.28.0

package com.saigou.grpc;

public interface FaceBoxOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FaceBox)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 类别标签
   * </pre>
   *
   * <code>string label = 1;</code>
   * @return The label.
   */
  String getLabel();
  /**
   * <pre>
   * 类别标签
   * </pre>
   *
   * <code>string label = 1;</code>
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <pre>
   * 边界框坐标归一化比例（0.0~1.0）
   * </pre>
   *
   * <code>.Point minPoint = 2;</code>
   * @return Whether the minPoint field is set.
   */
  boolean hasMinPoint();
  /**
   * <pre>
   * 边界框坐标归一化比例（0.0~1.0）
   * </pre>
   *
   * <code>.Point minPoint = 2;</code>
   * @return The minPoint.
   */
  Point getMinPoint();
  /**
   * <pre>
   * 边界框坐标归一化比例（0.0~1.0）
   * </pre>
   *
   * <code>.Point minPoint = 2;</code>
   */
  PointOrBuilder getMinPointOrBuilder();

  /**
   * <pre>
   * 右下角点
   * </pre>
   *
   * <code>.Point maxPoint = 3;</code>
   * @return Whether the maxPoint field is set.
   */
  boolean hasMaxPoint();
  /**
   * <pre>
   * 右下角点
   * </pre>
   *
   * <code>.Point maxPoint = 3;</code>
   * @return The maxPoint.
   */
  Point getMaxPoint();
  /**
   * <pre>
   * 右下角点
   * </pre>
   *
   * <code>.Point maxPoint = 3;</code>
   */
  PointOrBuilder getMaxPointOrBuilder();

  /**
   * <pre>
   * 置信度
   * </pre>
   *
   * <code>float score = 4;</code>
   * @return The score.
   */
  float getScore();

  /**
   * <pre>
   * 轨迹ID
   * </pre>
   *
   * <code>int64 track_id = 5;</code>
   * @return The trackId.
   */
  long getTrackId();

  /**
   * <pre>
   * 人脸ID
   * </pre>
   *
   * <code>int64 face_id = 6;</code>
   * @return The faceId.
   */
  long getFaceId();

  /**
   * <pre>
   * 表情ID（0～6）
   * </pre>
   *
   * <code>int64 expression_id = 7;</code>
   * @return The expressionId.
   */
  long getExpressionId();

  /**
   * <pre>
   * 表情特征
   * </pre>
   *
   * <code>string expression_feature = 8;</code>
   * @return The expressionFeature.
   */
  String getExpressionFeature();
  /**
   * <pre>
   * 表情特征
   * </pre>
   *
   * <code>string expression_feature = 8;</code>
   * @return The bytes for expressionFeature.
   */
  com.google.protobuf.ByteString
      getExpressionFeatureBytes();

  /**
   * <pre>
   * 额外数据(JSON格式)
   * </pre>
   *
   * <code>string data = 9;</code>
   * @return The data.
   */
  String getData();
  /**
   * <pre>
   * 额外数据(JSON格式)
   * </pre>
   *
   * <code>string data = 9;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
