// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: video.proto
// Protobuf Java Version: 4.28.0

package com.saigou.grpc;

public interface PersonBoxOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PersonBox)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 类别标签
   * </pre>
   *
   * <code>string label = 1;</code>
   * @return The label.
   */
  String getLabel();
  /**
   * <pre>
   * 类别标签
   * </pre>
   *
   * <code>string label = 1;</code>
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <pre>
   * 左上角点
   * </pre>
   *
   * <code>.Point minPoint = 2;</code>
   * @return Whether the minPoint field is set.
   */
  boolean hasMinPoint();
  /**
   * <pre>
   * 左上角点
   * </pre>
   *
   * <code>.Point minPoint = 2;</code>
   * @return The minPoint.
   */
  Point getMinPoint();
  /**
   * <pre>
   * 左上角点
   * </pre>
   *
   * <code>.Point minPoint = 2;</code>
   */
  PointOrBuilder getMinPointOrBuilder();

  /**
   * <pre>
   * 右下角点
   * </pre>
   *
   * <code>.Point maxPoint = 3;</code>
   * @return Whether the maxPoint field is set.
   */
  boolean hasMaxPoint();
  /**
   * <pre>
   * 右下角点
   * </pre>
   *
   * <code>.Point maxPoint = 3;</code>
   * @return The maxPoint.
   */
  Point getMaxPoint();
  /**
   * <pre>
   * 右下角点
   * </pre>
   *
   * <code>.Point maxPoint = 3;</code>
   */
  PointOrBuilder getMaxPointOrBuilder();

  /**
   * <pre>
   * 人体关键点
   * </pre>
   *
   * <code>repeated .Point points = 4;</code>
   */
  java.util.List<Point>
      getPointsList();
  /**
   * <pre>
   * 人体关键点
   * </pre>
   *
   * <code>repeated .Point points = 4;</code>
   */
  Point getPoints(int index);
  /**
   * <pre>
   * 人体关键点
   * </pre>
   *
   * <code>repeated .Point points = 4;</code>
   */
  int getPointsCount();
  /**
   * <pre>
   * 人体关键点
   * </pre>
   *
   * <code>repeated .Point points = 4;</code>
   */
  java.util.List<? extends PointOrBuilder>
      getPointsOrBuilderList();
  /**
   * <pre>
   * 人体关键点
   * </pre>
   *
   * <code>repeated .Point points = 4;</code>
   */
  PointOrBuilder getPointsOrBuilder(
      int index);

  /**
   * <pre>
   * 置信度
   * </pre>
   *
   * <code>float score = 5;</code>
   * @return The score.
   */
  float getScore();

  /**
   * <pre>
   * 轨迹ID
   * </pre>
   *
   * <code>int64 track_id = 6;</code>
   * @return The trackId.
   */
  long getTrackId();

  /**
   * <pre>
   * 姿态ID
   * </pre>
   *
   * <code>int64 attitude_id = 7;</code>
   * @return The attitudeId.
   */
  long getAttitudeId();

  /**
   * <pre>
   * 姿态特征
   * </pre>
   *
   * <code>string attitude_feature = 8;</code>
   * @return The attitudeFeature.
   */
  String getAttitudeFeature();
  /**
   * <pre>
   * 姿态特征
   * </pre>
   *
   * <code>string attitude_feature = 8;</code>
   * @return The bytes for attitudeFeature.
   */
  com.google.protobuf.ByteString
      getAttitudeFeatureBytes();

  /**
   * <pre>
   * 额外数据(JSON格式)
   * </pre>
   *
   * <code>string data = 9;</code>
   * @return The data.
   */
  String getData();
  /**
   * <pre>
   * 额外数据(JSON格式)
   * </pre>
   *
   * <code>string data = 9;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
