// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: video.proto
// Protobuf Java Version: 4.28.0

package com.saigou.grpc;

/**
 * Protobuf type {@code PersonBox}
 */
public final class PersonBox extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:PersonBox)
    PersonBoxOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 0,
      /* suffix= */ "",
      PersonBox.class.getName());
  }
  // Use PersonBox.newBuilder() to construct.
  private PersonBox(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PersonBox() {
    label_ = "";
    points_ = java.util.Collections.emptyList();
    attitudeFeature_ = "";
    data_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return VideoProto.internal_static_PersonBox_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return VideoProto.internal_static_PersonBox_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            PersonBox.class, Builder.class);
  }

  private int bitField0_;
  public static final int LABEL_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object label_ = "";
  /**
   * <pre>
   * 类别标签
   * </pre>
   *
   * <code>string label = 1;</code>
   * @return The label.
   */
  @Override
  public String getLabel() {
    Object ref = label_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      label_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 类别标签
   * </pre>
   *
   * <code>string label = 1;</code>
   * @return The bytes for label.
   */
  @Override
  public com.google.protobuf.ByteString
      getLabelBytes() {
    Object ref = label_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      label_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MINPOINT_FIELD_NUMBER = 2;
  private Point minPoint_;
  /**
   * <pre>
   * 左上角点
   * </pre>
   *
   * <code>.Point minPoint = 2;</code>
   * @return Whether the minPoint field is set.
   */
  @Override
  public boolean hasMinPoint() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * 左上角点
   * </pre>
   *
   * <code>.Point minPoint = 2;</code>
   * @return The minPoint.
   */
  @Override
  public Point getMinPoint() {
    return minPoint_ == null ? Point.getDefaultInstance() : minPoint_;
  }
  /**
   * <pre>
   * 左上角点
   * </pre>
   *
   * <code>.Point minPoint = 2;</code>
   */
  @Override
  public PointOrBuilder getMinPointOrBuilder() {
    return minPoint_ == null ? Point.getDefaultInstance() : minPoint_;
  }

  public static final int MAXPOINT_FIELD_NUMBER = 3;
  private Point maxPoint_;
  /**
   * <pre>
   * 右下角点
   * </pre>
   *
   * <code>.Point maxPoint = 3;</code>
   * @return Whether the maxPoint field is set.
   */
  @Override
  public boolean hasMaxPoint() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * 右下角点
   * </pre>
   *
   * <code>.Point maxPoint = 3;</code>
   * @return The maxPoint.
   */
  @Override
  public Point getMaxPoint() {
    return maxPoint_ == null ? Point.getDefaultInstance() : maxPoint_;
  }
  /**
   * <pre>
   * 右下角点
   * </pre>
   *
   * <code>.Point maxPoint = 3;</code>
   */
  @Override
  public PointOrBuilder getMaxPointOrBuilder() {
    return maxPoint_ == null ? Point.getDefaultInstance() : maxPoint_;
  }

  public static final int POINTS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<Point> points_;
  /**
   * <pre>
   * 人体关键点
   * </pre>
   *
   * <code>repeated .Point points = 4;</code>
   */
  @Override
  public java.util.List<Point> getPointsList() {
    return points_;
  }
  /**
   * <pre>
   * 人体关键点
   * </pre>
   *
   * <code>repeated .Point points = 4;</code>
   */
  @Override
  public java.util.List<? extends PointOrBuilder>
      getPointsOrBuilderList() {
    return points_;
  }
  /**
   * <pre>
   * 人体关键点
   * </pre>
   *
   * <code>repeated .Point points = 4;</code>
   */
  @Override
  public int getPointsCount() {
    return points_.size();
  }
  /**
   * <pre>
   * 人体关键点
   * </pre>
   *
   * <code>repeated .Point points = 4;</code>
   */
  @Override
  public Point getPoints(int index) {
    return points_.get(index);
  }
  /**
   * <pre>
   * 人体关键点
   * </pre>
   *
   * <code>repeated .Point points = 4;</code>
   */
  @Override
  public PointOrBuilder getPointsOrBuilder(
      int index) {
    return points_.get(index);
  }

  public static final int SCORE_FIELD_NUMBER = 5;
  private float score_ = 0F;
  /**
   * <pre>
   * 置信度
   * </pre>
   *
   * <code>float score = 5;</code>
   * @return The score.
   */
  @Override
  public float getScore() {
    return score_;
  }

  public static final int TRACK_ID_FIELD_NUMBER = 6;
  private long trackId_ = 0L;
  /**
   * <pre>
   * 轨迹ID
   * </pre>
   *
   * <code>int64 track_id = 6;</code>
   * @return The trackId.
   */
  @Override
  public long getTrackId() {
    return trackId_;
  }

  public static final int ATTITUDE_ID_FIELD_NUMBER = 7;
  private long attitudeId_ = 0L;
  /**
   * <pre>
   * 姿态ID
   * </pre>
   *
   * <code>int64 attitude_id = 7;</code>
   * @return The attitudeId.
   */
  @Override
  public long getAttitudeId() {
    return attitudeId_;
  }

  public static final int ATTITUDE_FEATURE_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile Object attitudeFeature_ = "";
  /**
   * <pre>
   * 姿态特征
   * </pre>
   *
   * <code>string attitude_feature = 8;</code>
   * @return The attitudeFeature.
   */
  @Override
  public String getAttitudeFeature() {
    Object ref = attitudeFeature_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      attitudeFeature_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 姿态特征
   * </pre>
   *
   * <code>string attitude_feature = 8;</code>
   * @return The bytes for attitudeFeature.
   */
  @Override
  public com.google.protobuf.ByteString
      getAttitudeFeatureBytes() {
    Object ref = attitudeFeature_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      attitudeFeature_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile Object data_ = "";
  /**
   * <pre>
   * 额外数据(JSON格式)
   * </pre>
   *
   * <code>string data = 9;</code>
   * @return The data.
   */
  @Override
  public String getData() {
    Object ref = data_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      data_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 额外数据(JSON格式)
   * </pre>
   *
   * <code>string data = 9;</code>
   * @return The bytes for data.
   */
  @Override
  public com.google.protobuf.ByteString
      getDataBytes() {
    Object ref = data_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      data_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(label_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, label_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getMinPoint());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getMaxPoint());
    }
    for (int i = 0; i < points_.size(); i++) {
      output.writeMessage(4, points_.get(i));
    }
    if (Float.floatToRawIntBits(score_) != 0) {
      output.writeFloat(5, score_);
    }
    if (trackId_ != 0L) {
      output.writeInt64(6, trackId_);
    }
    if (attitudeId_ != 0L) {
      output.writeInt64(7, attitudeId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(attitudeFeature_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, attitudeFeature_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(data_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, data_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(label_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, label_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMinPoint());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getMaxPoint());
    }
    for (int i = 0; i < points_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, points_.get(i));
    }
    if (Float.floatToRawIntBits(score_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(5, score_);
    }
    if (trackId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, trackId_);
    }
    if (attitudeId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, attitudeId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(attitudeFeature_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, attitudeFeature_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(data_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, data_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof PersonBox)) {
      return super.equals(obj);
    }
    PersonBox other = (PersonBox) obj;

    if (!getLabel()
        .equals(other.getLabel())) return false;
    if (hasMinPoint() != other.hasMinPoint()) return false;
    if (hasMinPoint()) {
      if (!getMinPoint()
          .equals(other.getMinPoint())) return false;
    }
    if (hasMaxPoint() != other.hasMaxPoint()) return false;
    if (hasMaxPoint()) {
      if (!getMaxPoint()
          .equals(other.getMaxPoint())) return false;
    }
    if (!getPointsList()
        .equals(other.getPointsList())) return false;
    if (Float.floatToIntBits(getScore())
        != Float.floatToIntBits(
            other.getScore())) return false;
    if (getTrackId()
        != other.getTrackId()) return false;
    if (getAttitudeId()
        != other.getAttitudeId()) return false;
    if (!getAttitudeFeature()
        .equals(other.getAttitudeFeature())) return false;
    if (!getData()
        .equals(other.getData())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LABEL_FIELD_NUMBER;
    hash = (53 * hash) + getLabel().hashCode();
    if (hasMinPoint()) {
      hash = (37 * hash) + MINPOINT_FIELD_NUMBER;
      hash = (53 * hash) + getMinPoint().hashCode();
    }
    if (hasMaxPoint()) {
      hash = (37 * hash) + MAXPOINT_FIELD_NUMBER;
      hash = (53 * hash) + getMaxPoint().hashCode();
    }
    if (getPointsCount() > 0) {
      hash = (37 * hash) + POINTS_FIELD_NUMBER;
      hash = (53 * hash) + getPointsList().hashCode();
    }
    hash = (37 * hash) + SCORE_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getScore());
    hash = (37 * hash) + TRACK_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTrackId());
    hash = (37 * hash) + ATTITUDE_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAttitudeId());
    hash = (37 * hash) + ATTITUDE_FEATURE_FIELD_NUMBER;
    hash = (53 * hash) + getAttitudeFeature().hashCode();
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static PersonBox parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PersonBox parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PersonBox parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PersonBox parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PersonBox parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PersonBox parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PersonBox parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static PersonBox parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static PersonBox parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static PersonBox parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static PersonBox parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static PersonBox parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(PersonBox prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PersonBox}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PersonBox)
      PersonBoxOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return VideoProto.internal_static_PersonBox_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return VideoProto.internal_static_PersonBox_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PersonBox.class, Builder.class);
    }

    // Construct using com.saigou.grpc.PersonBox.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getMinPointFieldBuilder();
        getMaxPointFieldBuilder();
        getPointsFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      label_ = "";
      minPoint_ = null;
      if (minPointBuilder_ != null) {
        minPointBuilder_.dispose();
        minPointBuilder_ = null;
      }
      maxPoint_ = null;
      if (maxPointBuilder_ != null) {
        maxPointBuilder_.dispose();
        maxPointBuilder_ = null;
      }
      if (pointsBuilder_ == null) {
        points_ = java.util.Collections.emptyList();
      } else {
        points_ = null;
        pointsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      score_ = 0F;
      trackId_ = 0L;
      attitudeId_ = 0L;
      attitudeFeature_ = "";
      data_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return VideoProto.internal_static_PersonBox_descriptor;
    }

    @Override
    public PersonBox getDefaultInstanceForType() {
      return PersonBox.getDefaultInstance();
    }

    @Override
    public PersonBox build() {
      PersonBox result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public PersonBox buildPartial() {
      PersonBox result = new PersonBox(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(PersonBox result) {
      if (pointsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          points_ = java.util.Collections.unmodifiableList(points_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.points_ = points_;
      } else {
        result.points_ = pointsBuilder_.build();
      }
    }

    private void buildPartial0(PersonBox result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.label_ = label_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.minPoint_ = minPointBuilder_ == null
            ? minPoint_
            : minPointBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.maxPoint_ = maxPointBuilder_ == null
            ? maxPoint_
            : maxPointBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.score_ = score_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.trackId_ = trackId_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.attitudeId_ = attitudeId_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.attitudeFeature_ = attitudeFeature_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.data_ = data_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof PersonBox) {
        return mergeFrom((PersonBox)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(PersonBox other) {
      if (other == PersonBox.getDefaultInstance()) return this;
      if (!other.getLabel().isEmpty()) {
        label_ = other.label_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasMinPoint()) {
        mergeMinPoint(other.getMinPoint());
      }
      if (other.hasMaxPoint()) {
        mergeMaxPoint(other.getMaxPoint());
      }
      if (pointsBuilder_ == null) {
        if (!other.points_.isEmpty()) {
          if (points_.isEmpty()) {
            points_ = other.points_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensurePointsIsMutable();
            points_.addAll(other.points_);
          }
          onChanged();
        }
      } else {
        if (!other.points_.isEmpty()) {
          if (pointsBuilder_.isEmpty()) {
            pointsBuilder_.dispose();
            pointsBuilder_ = null;
            points_ = other.points_;
            bitField0_ = (bitField0_ & ~0x00000008);
            pointsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getPointsFieldBuilder() : null;
          } else {
            pointsBuilder_.addAllMessages(other.points_);
          }
        }
      }
      if (other.getScore() != 0F) {
        setScore(other.getScore());
      }
      if (other.getTrackId() != 0L) {
        setTrackId(other.getTrackId());
      }
      if (other.getAttitudeId() != 0L) {
        setAttitudeId(other.getAttitudeId());
      }
      if (!other.getAttitudeFeature().isEmpty()) {
        attitudeFeature_ = other.attitudeFeature_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getData().isEmpty()) {
        data_ = other.data_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              label_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getMinPointFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getMaxPointFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              Point m =
                  input.readMessage(
                      Point.parser(),
                      extensionRegistry);
              if (pointsBuilder_ == null) {
                ensurePointsIsMutable();
                points_.add(m);
              } else {
                pointsBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 45: {
              score_ = input.readFloat();
              bitField0_ |= 0x00000010;
              break;
            } // case 45
            case 48: {
              trackId_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              attitudeId_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 66: {
              attitudeFeature_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              data_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object label_ = "";
    /**
     * <pre>
     * 类别标签
     * </pre>
     *
     * <code>string label = 1;</code>
     * @return The label.
     */
    public String getLabel() {
      Object ref = label_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        label_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 类别标签
     * </pre>
     *
     * <code>string label = 1;</code>
     * @return The bytes for label.
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      Object ref = label_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 类别标签
     * </pre>
     *
     * <code>string label = 1;</code>
     * @param value The label to set.
     * @return This builder for chaining.
     */
    public Builder setLabel(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      label_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 类别标签
     * </pre>
     *
     * <code>string label = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLabel() {
      label_ = getDefaultInstance().getLabel();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 类别标签
     * </pre>
     *
     * <code>string label = 1;</code>
     * @param value The bytes for label to set.
     * @return This builder for chaining.
     */
    public Builder setLabelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      label_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private Point minPoint_;
    private com.google.protobuf.SingleFieldBuilder<
        Point, Point.Builder, PointOrBuilder> minPointBuilder_;
    /**
     * <pre>
     * 左上角点
     * </pre>
     *
     * <code>.Point minPoint = 2;</code>
     * @return Whether the minPoint field is set.
     */
    public boolean hasMinPoint() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 左上角点
     * </pre>
     *
     * <code>.Point minPoint = 2;</code>
     * @return The minPoint.
     */
    public Point getMinPoint() {
      if (minPointBuilder_ == null) {
        return minPoint_ == null ? Point.getDefaultInstance() : minPoint_;
      } else {
        return minPointBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 左上角点
     * </pre>
     *
     * <code>.Point minPoint = 2;</code>
     */
    public Builder setMinPoint(Point value) {
      if (minPointBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        minPoint_ = value;
      } else {
        minPointBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 左上角点
     * </pre>
     *
     * <code>.Point minPoint = 2;</code>
     */
    public Builder setMinPoint(
        Point.Builder builderForValue) {
      if (minPointBuilder_ == null) {
        minPoint_ = builderForValue.build();
      } else {
        minPointBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 左上角点
     * </pre>
     *
     * <code>.Point minPoint = 2;</code>
     */
    public Builder mergeMinPoint(Point value) {
      if (minPointBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          minPoint_ != null &&
          minPoint_ != Point.getDefaultInstance()) {
          getMinPointBuilder().mergeFrom(value);
        } else {
          minPoint_ = value;
        }
      } else {
        minPointBuilder_.mergeFrom(value);
      }
      if (minPoint_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * 左上角点
     * </pre>
     *
     * <code>.Point minPoint = 2;</code>
     */
    public Builder clearMinPoint() {
      bitField0_ = (bitField0_ & ~0x00000002);
      minPoint_ = null;
      if (minPointBuilder_ != null) {
        minPointBuilder_.dispose();
        minPointBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 左上角点
     * </pre>
     *
     * <code>.Point minPoint = 2;</code>
     */
    public Point.Builder getMinPointBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getMinPointFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 左上角点
     * </pre>
     *
     * <code>.Point minPoint = 2;</code>
     */
    public PointOrBuilder getMinPointOrBuilder() {
      if (minPointBuilder_ != null) {
        return minPointBuilder_.getMessageOrBuilder();
      } else {
        return minPoint_ == null ?
            Point.getDefaultInstance() : minPoint_;
      }
    }
    /**
     * <pre>
     * 左上角点
     * </pre>
     *
     * <code>.Point minPoint = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        Point, Point.Builder, PointOrBuilder>
        getMinPointFieldBuilder() {
      if (minPointBuilder_ == null) {
        minPointBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            Point, Point.Builder, PointOrBuilder>(
                getMinPoint(),
                getParentForChildren(),
                isClean());
        minPoint_ = null;
      }
      return minPointBuilder_;
    }

    private Point maxPoint_;
    private com.google.protobuf.SingleFieldBuilder<
        Point, Point.Builder, PointOrBuilder> maxPointBuilder_;
    /**
     * <pre>
     * 右下角点
     * </pre>
     *
     * <code>.Point maxPoint = 3;</code>
     * @return Whether the maxPoint field is set.
     */
    public boolean hasMaxPoint() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * 右下角点
     * </pre>
     *
     * <code>.Point maxPoint = 3;</code>
     * @return The maxPoint.
     */
    public Point getMaxPoint() {
      if (maxPointBuilder_ == null) {
        return maxPoint_ == null ? Point.getDefaultInstance() : maxPoint_;
      } else {
        return maxPointBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 右下角点
     * </pre>
     *
     * <code>.Point maxPoint = 3;</code>
     */
    public Builder setMaxPoint(Point value) {
      if (maxPointBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        maxPoint_ = value;
      } else {
        maxPointBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 右下角点
     * </pre>
     *
     * <code>.Point maxPoint = 3;</code>
     */
    public Builder setMaxPoint(
        Point.Builder builderForValue) {
      if (maxPointBuilder_ == null) {
        maxPoint_ = builderForValue.build();
      } else {
        maxPointBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 右下角点
     * </pre>
     *
     * <code>.Point maxPoint = 3;</code>
     */
    public Builder mergeMaxPoint(Point value) {
      if (maxPointBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          maxPoint_ != null &&
          maxPoint_ != Point.getDefaultInstance()) {
          getMaxPointBuilder().mergeFrom(value);
        } else {
          maxPoint_ = value;
        }
      } else {
        maxPointBuilder_.mergeFrom(value);
      }
      if (maxPoint_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * 右下角点
     * </pre>
     *
     * <code>.Point maxPoint = 3;</code>
     */
    public Builder clearMaxPoint() {
      bitField0_ = (bitField0_ & ~0x00000004);
      maxPoint_ = null;
      if (maxPointBuilder_ != null) {
        maxPointBuilder_.dispose();
        maxPointBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 右下角点
     * </pre>
     *
     * <code>.Point maxPoint = 3;</code>
     */
    public Point.Builder getMaxPointBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getMaxPointFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 右下角点
     * </pre>
     *
     * <code>.Point maxPoint = 3;</code>
     */
    public PointOrBuilder getMaxPointOrBuilder() {
      if (maxPointBuilder_ != null) {
        return maxPointBuilder_.getMessageOrBuilder();
      } else {
        return maxPoint_ == null ?
            Point.getDefaultInstance() : maxPoint_;
      }
    }
    /**
     * <pre>
     * 右下角点
     * </pre>
     *
     * <code>.Point maxPoint = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        Point, Point.Builder, PointOrBuilder>
        getMaxPointFieldBuilder() {
      if (maxPointBuilder_ == null) {
        maxPointBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            Point, Point.Builder, PointOrBuilder>(
                getMaxPoint(),
                getParentForChildren(),
                isClean());
        maxPoint_ = null;
      }
      return maxPointBuilder_;
    }

    private java.util.List<Point> points_ =
      java.util.Collections.emptyList();
    private void ensurePointsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        points_ = new java.util.ArrayList<Point>(points_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        Point, Point.Builder, PointOrBuilder> pointsBuilder_;

    /**
     * <pre>
     * 人体关键点
     * </pre>
     *
     * <code>repeated .Point points = 4;</code>
     */
    public java.util.List<Point> getPointsList() {
      if (pointsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(points_);
      } else {
        return pointsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 人体关键点
     * </pre>
     *
     * <code>repeated .Point points = 4;</code>
     */
    public int getPointsCount() {
      if (pointsBuilder_ == null) {
        return points_.size();
      } else {
        return pointsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 人体关键点
     * </pre>
     *
     * <code>repeated .Point points = 4;</code>
     */
    public Point getPoints(int index) {
      if (pointsBuilder_ == null) {
        return points_.get(index);
      } else {
        return pointsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 人体关键点
     * </pre>
     *
     * <code>repeated .Point points = 4;</code>
     */
    public Builder setPoints(
        int index, Point value) {
      if (pointsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePointsIsMutable();
        points_.set(index, value);
        onChanged();
      } else {
        pointsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 人体关键点
     * </pre>
     *
     * <code>repeated .Point points = 4;</code>
     */
    public Builder setPoints(
        int index, Point.Builder builderForValue) {
      if (pointsBuilder_ == null) {
        ensurePointsIsMutable();
        points_.set(index, builderForValue.build());
        onChanged();
      } else {
        pointsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 人体关键点
     * </pre>
     *
     * <code>repeated .Point points = 4;</code>
     */
    public Builder addPoints(Point value) {
      if (pointsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePointsIsMutable();
        points_.add(value);
        onChanged();
      } else {
        pointsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 人体关键点
     * </pre>
     *
     * <code>repeated .Point points = 4;</code>
     */
    public Builder addPoints(
        int index, Point value) {
      if (pointsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePointsIsMutable();
        points_.add(index, value);
        onChanged();
      } else {
        pointsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 人体关键点
     * </pre>
     *
     * <code>repeated .Point points = 4;</code>
     */
    public Builder addPoints(
        Point.Builder builderForValue) {
      if (pointsBuilder_ == null) {
        ensurePointsIsMutable();
        points_.add(builderForValue.build());
        onChanged();
      } else {
        pointsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 人体关键点
     * </pre>
     *
     * <code>repeated .Point points = 4;</code>
     */
    public Builder addPoints(
        int index, Point.Builder builderForValue) {
      if (pointsBuilder_ == null) {
        ensurePointsIsMutable();
        points_.add(index, builderForValue.build());
        onChanged();
      } else {
        pointsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 人体关键点
     * </pre>
     *
     * <code>repeated .Point points = 4;</code>
     */
    public Builder addAllPoints(
        Iterable<? extends Point> values) {
      if (pointsBuilder_ == null) {
        ensurePointsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, points_);
        onChanged();
      } else {
        pointsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 人体关键点
     * </pre>
     *
     * <code>repeated .Point points = 4;</code>
     */
    public Builder clearPoints() {
      if (pointsBuilder_ == null) {
        points_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        pointsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 人体关键点
     * </pre>
     *
     * <code>repeated .Point points = 4;</code>
     */
    public Builder removePoints(int index) {
      if (pointsBuilder_ == null) {
        ensurePointsIsMutable();
        points_.remove(index);
        onChanged();
      } else {
        pointsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 人体关键点
     * </pre>
     *
     * <code>repeated .Point points = 4;</code>
     */
    public Point.Builder getPointsBuilder(
        int index) {
      return getPointsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 人体关键点
     * </pre>
     *
     * <code>repeated .Point points = 4;</code>
     */
    public PointOrBuilder getPointsOrBuilder(
        int index) {
      if (pointsBuilder_ == null) {
        return points_.get(index);  } else {
        return pointsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 人体关键点
     * </pre>
     *
     * <code>repeated .Point points = 4;</code>
     */
    public java.util.List<? extends PointOrBuilder>
         getPointsOrBuilderList() {
      if (pointsBuilder_ != null) {
        return pointsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(points_);
      }
    }
    /**
     * <pre>
     * 人体关键点
     * </pre>
     *
     * <code>repeated .Point points = 4;</code>
     */
    public Point.Builder addPointsBuilder() {
      return getPointsFieldBuilder().addBuilder(
          Point.getDefaultInstance());
    }
    /**
     * <pre>
     * 人体关键点
     * </pre>
     *
     * <code>repeated .Point points = 4;</code>
     */
    public Point.Builder addPointsBuilder(
        int index) {
      return getPointsFieldBuilder().addBuilder(
          index, Point.getDefaultInstance());
    }
    /**
     * <pre>
     * 人体关键点
     * </pre>
     *
     * <code>repeated .Point points = 4;</code>
     */
    public java.util.List<Point.Builder>
         getPointsBuilderList() {
      return getPointsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        Point, Point.Builder, PointOrBuilder>
        getPointsFieldBuilder() {
      if (pointsBuilder_ == null) {
        pointsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            Point, Point.Builder, PointOrBuilder>(
                points_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        points_ = null;
      }
      return pointsBuilder_;
    }

    private float score_ ;
    /**
     * <pre>
     * 置信度
     * </pre>
     *
     * <code>float score = 5;</code>
     * @return The score.
     */
    @Override
    public float getScore() {
      return score_;
    }
    /**
     * <pre>
     * 置信度
     * </pre>
     *
     * <code>float score = 5;</code>
     * @param value The score to set.
     * @return This builder for chaining.
     */
    public Builder setScore(float value) {

      score_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 置信度
     * </pre>
     *
     * <code>float score = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearScore() {
      bitField0_ = (bitField0_ & ~0x00000010);
      score_ = 0F;
      onChanged();
      return this;
    }

    private long trackId_ ;
    /**
     * <pre>
     * 轨迹ID
     * </pre>
     *
     * <code>int64 track_id = 6;</code>
     * @return The trackId.
     */
    @Override
    public long getTrackId() {
      return trackId_;
    }
    /**
     * <pre>
     * 轨迹ID
     * </pre>
     *
     * <code>int64 track_id = 6;</code>
     * @param value The trackId to set.
     * @return This builder for chaining.
     */
    public Builder setTrackId(long value) {

      trackId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 轨迹ID
     * </pre>
     *
     * <code>int64 track_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrackId() {
      bitField0_ = (bitField0_ & ~0x00000020);
      trackId_ = 0L;
      onChanged();
      return this;
    }

    private long attitudeId_ ;
    /**
     * <pre>
     * 姿态ID
     * </pre>
     *
     * <code>int64 attitude_id = 7;</code>
     * @return The attitudeId.
     */
    @Override
    public long getAttitudeId() {
      return attitudeId_;
    }
    /**
     * <pre>
     * 姿态ID
     * </pre>
     *
     * <code>int64 attitude_id = 7;</code>
     * @param value The attitudeId to set.
     * @return This builder for chaining.
     */
    public Builder setAttitudeId(long value) {

      attitudeId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 姿态ID
     * </pre>
     *
     * <code>int64 attitude_id = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearAttitudeId() {
      bitField0_ = (bitField0_ & ~0x00000040);
      attitudeId_ = 0L;
      onChanged();
      return this;
    }

    private Object attitudeFeature_ = "";
    /**
     * <pre>
     * 姿态特征
     * </pre>
     *
     * <code>string attitude_feature = 8;</code>
     * @return The attitudeFeature.
     */
    public String getAttitudeFeature() {
      Object ref = attitudeFeature_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        attitudeFeature_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 姿态特征
     * </pre>
     *
     * <code>string attitude_feature = 8;</code>
     * @return The bytes for attitudeFeature.
     */
    public com.google.protobuf.ByteString
        getAttitudeFeatureBytes() {
      Object ref = attitudeFeature_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        attitudeFeature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 姿态特征
     * </pre>
     *
     * <code>string attitude_feature = 8;</code>
     * @param value The attitudeFeature to set.
     * @return This builder for chaining.
     */
    public Builder setAttitudeFeature(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      attitudeFeature_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 姿态特征
     * </pre>
     *
     * <code>string attitude_feature = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearAttitudeFeature() {
      attitudeFeature_ = getDefaultInstance().getAttitudeFeature();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 姿态特征
     * </pre>
     *
     * <code>string attitude_feature = 8;</code>
     * @param value The bytes for attitudeFeature to set.
     * @return This builder for chaining.
     */
    public Builder setAttitudeFeatureBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      attitudeFeature_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private Object data_ = "";
    /**
     * <pre>
     * 额外数据(JSON格式)
     * </pre>
     *
     * <code>string data = 9;</code>
     * @return The data.
     */
    public String getData() {
      Object ref = data_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        data_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 额外数据(JSON格式)
     * </pre>
     *
     * <code>string data = 9;</code>
     * @return The bytes for data.
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 额外数据(JSON格式)
     * </pre>
     *
     * <code>string data = 9;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      data_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 额外数据(JSON格式)
     * </pre>
     *
     * <code>string data = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      data_ = getDefaultInstance().getData();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 额外数据(JSON格式)
     * </pre>
     *
     * <code>string data = 9;</code>
     * @param value The bytes for data to set.
     * @return This builder for chaining.
     */
    public Builder setDataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      data_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PersonBox)
  }

  // @@protoc_insertion_point(class_scope:PersonBox)
  private static final PersonBox DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new PersonBox();
  }

  public static PersonBox getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PersonBox>
      PARSER = new com.google.protobuf.AbstractParser<PersonBox>() {
    @Override
    public PersonBox parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PersonBox> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<PersonBox> getParserForType() {
    return PARSER;
  }

  @Override
  public PersonBox getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

