// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: video.proto
// Protobuf Java Version: 4.28.0

package com.saigou.grpc;

public interface PointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Point)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float x = 1;</code>
   * @return The x.
   */
  float getX();

  /**
   * <code>float y = 2;</code>
   * @return The y.
   */
  float getY();
}
