// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: video.proto
// Protobuf Java Version: 4.28.0

package com.saigou.grpc;

public interface VideoFrameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VideoFrame)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 图片帧数据
   * </pre>
   *
   * <code>bytes image_data = 1;</code>
   * @return The imageData.
   */
  com.google.protobuf.ByteString getImageData();

  /**
   * <pre>
   * 时间戳（毫秒）
   * </pre>
   *
   * <code>int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <pre>
   * 算法类别
   * </pre>
   *
   * <code>repeated .Algorithm algorithms = 3;</code>
   */
  java.util.List<Algorithm>
      getAlgorithmsList();
  /**
   * <pre>
   * 算法类别
   * </pre>
   *
   * <code>repeated .Algorithm algorithms = 3;</code>
   */
  Algorithm getAlgorithms(int index);
  /**
   * <pre>
   * 算法类别
   * </pre>
   *
   * <code>repeated .Algorithm algorithms = 3;</code>
   */
  int getAlgorithmsCount();
  /**
   * <pre>
   * 算法类别
   * </pre>
   *
   * <code>repeated .Algorithm algorithms = 3;</code>
   */
  java.util.List<? extends AlgorithmOrBuilder>
      getAlgorithmsOrBuilderList();
  /**
   * <pre>
   * 算法类别
   * </pre>
   *
   * <code>repeated .Algorithm algorithms = 3;</code>
   */
  AlgorithmOrBuilder getAlgorithmsOrBuilder(
      int index);

  /**
   * <pre>
   * 高度
   * </pre>
   *
   * <code>int64 height = 4;</code>
   * @return The height.
   */
  long getHeight();

  /**
   * <pre>
   * 宽度
   * </pre>
   *
   * <code>int64 width = 5;</code>
   * @return The width.
   */
  long getWidth();
}
