// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: video.proto
// Protobuf Java Version: 4.28.0

package com.saigou.grpc;

/**
 * Protobuf type {@code VideoFrame}
 */
public final class VideoFrame extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:VideoFrame)
    VideoFrameOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 0,
      /* suffix= */ "",
      VideoFrame.class.getName());
  }
  // Use VideoFrame.newBuilder() to construct.
  private VideoFrame(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private VideoFrame() {
    imageData_ = com.google.protobuf.ByteString.EMPTY;
    algorithms_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return VideoProto.internal_static_VideoFrame_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return VideoProto.internal_static_VideoFrame_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            VideoFrame.class, Builder.class);
  }

  public static final int IMAGE_DATA_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString imageData_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * 图片帧数据
   * </pre>
   *
   * <code>bytes image_data = 1;</code>
   * @return The imageData.
   */
  @Override
  public com.google.protobuf.ByteString getImageData() {
    return imageData_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private long timestamp_ = 0L;
  /**
   * <pre>
   * 时间戳（毫秒）
   * </pre>
   *
   * <code>int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  @Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int ALGORITHMS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<Algorithm> algorithms_;
  /**
   * <pre>
   * 算法类别
   * </pre>
   *
   * <code>repeated .Algorithm algorithms = 3;</code>
   */
  @Override
  public java.util.List<Algorithm> getAlgorithmsList() {
    return algorithms_;
  }
  /**
   * <pre>
   * 算法类别
   * </pre>
   *
   * <code>repeated .Algorithm algorithms = 3;</code>
   */
  @Override
  public java.util.List<? extends AlgorithmOrBuilder>
      getAlgorithmsOrBuilderList() {
    return algorithms_;
  }
  /**
   * <pre>
   * 算法类别
   * </pre>
   *
   * <code>repeated .Algorithm algorithms = 3;</code>
   */
  @Override
  public int getAlgorithmsCount() {
    return algorithms_.size();
  }
  /**
   * <pre>
   * 算法类别
   * </pre>
   *
   * <code>repeated .Algorithm algorithms = 3;</code>
   */
  @Override
  public Algorithm getAlgorithms(int index) {
    return algorithms_.get(index);
  }
  /**
   * <pre>
   * 算法类别
   * </pre>
   *
   * <code>repeated .Algorithm algorithms = 3;</code>
   */
  @Override
  public AlgorithmOrBuilder getAlgorithmsOrBuilder(
      int index) {
    return algorithms_.get(index);
  }

  public static final int HEIGHT_FIELD_NUMBER = 4;
  private long height_ = 0L;
  /**
   * <pre>
   * 高度
   * </pre>
   *
   * <code>int64 height = 4;</code>
   * @return The height.
   */
  @Override
  public long getHeight() {
    return height_;
  }

  public static final int WIDTH_FIELD_NUMBER = 5;
  private long width_ = 0L;
  /**
   * <pre>
   * 宽度
   * </pre>
   *
   * <code>int64 width = 5;</code>
   * @return The width.
   */
  @Override
  public long getWidth() {
    return width_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!imageData_.isEmpty()) {
      output.writeBytes(1, imageData_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(2, timestamp_);
    }
    for (int i = 0; i < algorithms_.size(); i++) {
      output.writeMessage(3, algorithms_.get(i));
    }
    if (height_ != 0L) {
      output.writeInt64(4, height_);
    }
    if (width_ != 0L) {
      output.writeInt64(5, width_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!imageData_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, imageData_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, timestamp_);
    }
    for (int i = 0; i < algorithms_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, algorithms_.get(i));
    }
    if (height_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, height_);
    }
    if (width_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, width_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof VideoFrame)) {
      return super.equals(obj);
    }
    VideoFrame other = (VideoFrame) obj;

    if (!getImageData()
        .equals(other.getImageData())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getAlgorithmsList()
        .equals(other.getAlgorithmsList())) return false;
    if (getHeight()
        != other.getHeight()) return false;
    if (getWidth()
        != other.getWidth()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IMAGE_DATA_FIELD_NUMBER;
    hash = (53 * hash) + getImageData().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    if (getAlgorithmsCount() > 0) {
      hash = (37 * hash) + ALGORITHMS_FIELD_NUMBER;
      hash = (53 * hash) + getAlgorithmsList().hashCode();
    }
    hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getHeight());
    hash = (37 * hash) + WIDTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getWidth());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static VideoFrame parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VideoFrame parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VideoFrame parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VideoFrame parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VideoFrame parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VideoFrame parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VideoFrame parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static VideoFrame parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static VideoFrame parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static VideoFrame parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static VideoFrame parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static VideoFrame parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(VideoFrame prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code VideoFrame}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:VideoFrame)
      VideoFrameOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return VideoProto.internal_static_VideoFrame_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return VideoProto.internal_static_VideoFrame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              VideoFrame.class, Builder.class);
    }

    // Construct using com.saigou.grpc.VideoFrame.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      imageData_ = com.google.protobuf.ByteString.EMPTY;
      timestamp_ = 0L;
      if (algorithmsBuilder_ == null) {
        algorithms_ = java.util.Collections.emptyList();
      } else {
        algorithms_ = null;
        algorithmsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      height_ = 0L;
      width_ = 0L;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return VideoProto.internal_static_VideoFrame_descriptor;
    }

    @Override
    public VideoFrame getDefaultInstanceForType() {
      return VideoFrame.getDefaultInstance();
    }

    @Override
    public VideoFrame build() {
      VideoFrame result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public VideoFrame buildPartial() {
      VideoFrame result = new VideoFrame(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(VideoFrame result) {
      if (algorithmsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          algorithms_ = java.util.Collections.unmodifiableList(algorithms_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.algorithms_ = algorithms_;
      } else {
        result.algorithms_ = algorithmsBuilder_.build();
      }
    }

    private void buildPartial0(VideoFrame result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.imageData_ = imageData_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.timestamp_ = timestamp_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.height_ = height_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.width_ = width_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof VideoFrame) {
        return mergeFrom((VideoFrame)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(VideoFrame other) {
      if (other == VideoFrame.getDefaultInstance()) return this;
      if (other.getImageData() != com.google.protobuf.ByteString.EMPTY) {
        setImageData(other.getImageData());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (algorithmsBuilder_ == null) {
        if (!other.algorithms_.isEmpty()) {
          if (algorithms_.isEmpty()) {
            algorithms_ = other.algorithms_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureAlgorithmsIsMutable();
            algorithms_.addAll(other.algorithms_);
          }
          onChanged();
        }
      } else {
        if (!other.algorithms_.isEmpty()) {
          if (algorithmsBuilder_.isEmpty()) {
            algorithmsBuilder_.dispose();
            algorithmsBuilder_ = null;
            algorithms_ = other.algorithms_;
            bitField0_ = (bitField0_ & ~0x00000004);
            algorithmsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getAlgorithmsFieldBuilder() : null;
          } else {
            algorithmsBuilder_.addAllMessages(other.algorithms_);
          }
        }
      }
      if (other.getHeight() != 0L) {
        setHeight(other.getHeight());
      }
      if (other.getWidth() != 0L) {
        setWidth(other.getWidth());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              imageData_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              Algorithm m =
                  input.readMessage(
                      Algorithm.parser(),
                      extensionRegistry);
              if (algorithmsBuilder_ == null) {
                ensureAlgorithmsIsMutable();
                algorithms_.add(m);
              } else {
                algorithmsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 32: {
              height_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              width_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString imageData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 图片帧数据
     * </pre>
     *
     * <code>bytes image_data = 1;</code>
     * @return The imageData.
     */
    @Override
    public com.google.protobuf.ByteString getImageData() {
      return imageData_;
    }
    /**
     * <pre>
     * 图片帧数据
     * </pre>
     *
     * <code>bytes image_data = 1;</code>
     * @param value The imageData to set.
     * @return This builder for chaining.
     */
    public Builder setImageData(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      imageData_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 图片帧数据
     * </pre>
     *
     * <code>bytes image_data = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearImageData() {
      bitField0_ = (bitField0_ & ~0x00000001);
      imageData_ = getDefaultInstance().getImageData();
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <pre>
     * 时间戳（毫秒）
     * </pre>
     *
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    @Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * 时间戳（毫秒）
     * </pre>
     *
     * <code>int64 timestamp = 2;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 时间戳（毫秒）
     * </pre>
     *
     * <code>int64 timestamp = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000002);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<Algorithm> algorithms_ =
      java.util.Collections.emptyList();
    private void ensureAlgorithmsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        algorithms_ = new java.util.ArrayList<Algorithm>(algorithms_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        Algorithm, Algorithm.Builder, AlgorithmOrBuilder> algorithmsBuilder_;

    /**
     * <pre>
     * 算法类别
     * </pre>
     *
     * <code>repeated .Algorithm algorithms = 3;</code>
     */
    public java.util.List<Algorithm> getAlgorithmsList() {
      if (algorithmsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(algorithms_);
      } else {
        return algorithmsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 算法类别
     * </pre>
     *
     * <code>repeated .Algorithm algorithms = 3;</code>
     */
    public int getAlgorithmsCount() {
      if (algorithmsBuilder_ == null) {
        return algorithms_.size();
      } else {
        return algorithmsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 算法类别
     * </pre>
     *
     * <code>repeated .Algorithm algorithms = 3;</code>
     */
    public Algorithm getAlgorithms(int index) {
      if (algorithmsBuilder_ == null) {
        return algorithms_.get(index);
      } else {
        return algorithmsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 算法类别
     * </pre>
     *
     * <code>repeated .Algorithm algorithms = 3;</code>
     */
    public Builder setAlgorithms(
        int index, Algorithm value) {
      if (algorithmsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAlgorithmsIsMutable();
        algorithms_.set(index, value);
        onChanged();
      } else {
        algorithmsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 算法类别
     * </pre>
     *
     * <code>repeated .Algorithm algorithms = 3;</code>
     */
    public Builder setAlgorithms(
        int index, Algorithm.Builder builderForValue) {
      if (algorithmsBuilder_ == null) {
        ensureAlgorithmsIsMutable();
        algorithms_.set(index, builderForValue.build());
        onChanged();
      } else {
        algorithmsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 算法类别
     * </pre>
     *
     * <code>repeated .Algorithm algorithms = 3;</code>
     */
    public Builder addAlgorithms(Algorithm value) {
      if (algorithmsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAlgorithmsIsMutable();
        algorithms_.add(value);
        onChanged();
      } else {
        algorithmsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 算法类别
     * </pre>
     *
     * <code>repeated .Algorithm algorithms = 3;</code>
     */
    public Builder addAlgorithms(
        int index, Algorithm value) {
      if (algorithmsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAlgorithmsIsMutable();
        algorithms_.add(index, value);
        onChanged();
      } else {
        algorithmsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 算法类别
     * </pre>
     *
     * <code>repeated .Algorithm algorithms = 3;</code>
     */
    public Builder addAlgorithms(
        Algorithm.Builder builderForValue) {
      if (algorithmsBuilder_ == null) {
        ensureAlgorithmsIsMutable();
        algorithms_.add(builderForValue.build());
        onChanged();
      } else {
        algorithmsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 算法类别
     * </pre>
     *
     * <code>repeated .Algorithm algorithms = 3;</code>
     */
    public Builder addAlgorithms(
        int index, Algorithm.Builder builderForValue) {
      if (algorithmsBuilder_ == null) {
        ensureAlgorithmsIsMutable();
        algorithms_.add(index, builderForValue.build());
        onChanged();
      } else {
        algorithmsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 算法类别
     * </pre>
     *
     * <code>repeated .Algorithm algorithms = 3;</code>
     */
    public Builder addAllAlgorithms(
        Iterable<? extends Algorithm> values) {
      if (algorithmsBuilder_ == null) {
        ensureAlgorithmsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, algorithms_);
        onChanged();
      } else {
        algorithmsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 算法类别
     * </pre>
     *
     * <code>repeated .Algorithm algorithms = 3;</code>
     */
    public Builder clearAlgorithms() {
      if (algorithmsBuilder_ == null) {
        algorithms_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        algorithmsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 算法类别
     * </pre>
     *
     * <code>repeated .Algorithm algorithms = 3;</code>
     */
    public Builder removeAlgorithms(int index) {
      if (algorithmsBuilder_ == null) {
        ensureAlgorithmsIsMutable();
        algorithms_.remove(index);
        onChanged();
      } else {
        algorithmsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 算法类别
     * </pre>
     *
     * <code>repeated .Algorithm algorithms = 3;</code>
     */
    public Algorithm.Builder getAlgorithmsBuilder(
        int index) {
      return getAlgorithmsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 算法类别
     * </pre>
     *
     * <code>repeated .Algorithm algorithms = 3;</code>
     */
    public AlgorithmOrBuilder getAlgorithmsOrBuilder(
        int index) {
      if (algorithmsBuilder_ == null) {
        return algorithms_.get(index);  } else {
        return algorithmsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 算法类别
     * </pre>
     *
     * <code>repeated .Algorithm algorithms = 3;</code>
     */
    public java.util.List<? extends AlgorithmOrBuilder>
         getAlgorithmsOrBuilderList() {
      if (algorithmsBuilder_ != null) {
        return algorithmsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(algorithms_);
      }
    }
    /**
     * <pre>
     * 算法类别
     * </pre>
     *
     * <code>repeated .Algorithm algorithms = 3;</code>
     */
    public Algorithm.Builder addAlgorithmsBuilder() {
      return getAlgorithmsFieldBuilder().addBuilder(
          Algorithm.getDefaultInstance());
    }
    /**
     * <pre>
     * 算法类别
     * </pre>
     *
     * <code>repeated .Algorithm algorithms = 3;</code>
     */
    public Algorithm.Builder addAlgorithmsBuilder(
        int index) {
      return getAlgorithmsFieldBuilder().addBuilder(
          index, Algorithm.getDefaultInstance());
    }
    /**
     * <pre>
     * 算法类别
     * </pre>
     *
     * <code>repeated .Algorithm algorithms = 3;</code>
     */
    public java.util.List<Algorithm.Builder>
         getAlgorithmsBuilderList() {
      return getAlgorithmsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        Algorithm, Algorithm.Builder, AlgorithmOrBuilder>
        getAlgorithmsFieldBuilder() {
      if (algorithmsBuilder_ == null) {
        algorithmsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            Algorithm, Algorithm.Builder, AlgorithmOrBuilder>(
                algorithms_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        algorithms_ = null;
      }
      return algorithmsBuilder_;
    }

    private long height_ ;
    /**
     * <pre>
     * 高度
     * </pre>
     *
     * <code>int64 height = 4;</code>
     * @return The height.
     */
    @Override
    public long getHeight() {
      return height_;
    }
    /**
     * <pre>
     * 高度
     * </pre>
     *
     * <code>int64 height = 4;</code>
     * @param value The height to set.
     * @return This builder for chaining.
     */
    public Builder setHeight(long value) {

      height_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 高度
     * </pre>
     *
     * <code>int64 height = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeight() {
      bitField0_ = (bitField0_ & ~0x00000008);
      height_ = 0L;
      onChanged();
      return this;
    }

    private long width_ ;
    /**
     * <pre>
     * 宽度
     * </pre>
     *
     * <code>int64 width = 5;</code>
     * @return The width.
     */
    @Override
    public long getWidth() {
      return width_;
    }
    /**
     * <pre>
     * 宽度
     * </pre>
     *
     * <code>int64 width = 5;</code>
     * @param value The width to set.
     * @return This builder for chaining.
     */
    public Builder setWidth(long value) {

      width_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 宽度
     * </pre>
     *
     * <code>int64 width = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearWidth() {
      bitField0_ = (bitField0_ & ~0x00000010);
      width_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:VideoFrame)
  }

  // @@protoc_insertion_point(class_scope:VideoFrame)
  private static final VideoFrame DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new VideoFrame();
  }

  public static VideoFrame getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VideoFrame>
      PARSER = new com.google.protobuf.AbstractParser<VideoFrame>() {
    @Override
    public VideoFrame parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<VideoFrame> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<VideoFrame> getParserForType() {
    return PARSER;
  }

  @Override
  public VideoFrame getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

