// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: video.proto
// Protobuf Java Version: 4.28.0

package com.saigou.grpc;

public final class VideoProto {
  private VideoProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 0,
      /* suffix= */ "",
      VideoProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VideoFrame_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_VideoFrame_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnalysisResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AnalysisResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BoundingBox_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BoundingBox_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013video.proto\"k\n\nVideoFrame\022\022\n\nimage_dat" +
      "a\030\001 \001(\014\022\021\n\ttimestamp\030\002 \001(\003\022\027\n\017algorithms" +
      "_type\030\003 \001(\003\022\016\n\006height\030\004 \001(\003\022\r\n\005width\030\005 \001" +
      "(\003\"b\n\016AnalysisResult\022\021\n\ttimestamp\030\001 \001(\003\022" +
      "\033\n\005boxes\030\002 \003(\0132\014.BoundingBox\022\014\n\004data\030\003 \001" +
      "(\t\022\022\n\nimage_data\030\004 \001(\014\"\200\001\n\013BoundingBox\022\r" +
      "\n\005label\030\001 \001(\t\022\t\n\001x\030\002 \001(\003\022\t\n\001y\030\003 \001(\003\022\r\n\005w" +
      "idth\030\004 \001(\003\022\016\n\006height\030\005 \001(\003\022\r\n\005score\030\006 \001(" +
      "\002\022\020\n\010track_id\030\007 \001(\t\022\014\n\004data\030\010 \001(\t2B\n\016Vid" +
      "eoProcessor\0220\n\014ProcessFrame\022\013.VideoFrame" +
      "\032\017.AnalysisResult(\0010\001B\037\n\017com.saigou.grpc" +
      "B\nVideoProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_VideoFrame_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VideoFrame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_VideoFrame_descriptor,
        new String[] { "ImageData", "Timestamp", "AlgorithmsType", "Height", "Width", });
    internal_static_AnalysisResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AnalysisResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AnalysisResult_descriptor,
        new String[] { "Timestamp", "Boxes", "Data", "ImageData", });
    internal_static_BoundingBox_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_BoundingBox_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BoundingBox_descriptor,
        new String[] { "Label", "X", "Y", "Width", "Height", "Score", "TrackId", "Data", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
